/*
 * File: app/store/storeTeam.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeTeam', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelTeam'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        model: 'MyApp.model.modelTeam',
        storeId: 'storeTeam',
        proxy: {
            type: 'jsonp',
            url: 'http://192.168.43.237/as2PhP/team.php',
            reader: {
                type: 'json',
                rootProperty: 'ptm'
            }
        }
    }
});