/*
 * File: app/view/containerMyVideos.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerMyVideos', {
    extend: 'Ext.Container',
    alias: 'widget.containermyvideos',

    config: {
        html: '<canvas id="cosa" width=500px height=500px></canvas> ',
        id: 'containerMyVideos',
        layout: {
            type: 'fit'
        },
        listeners: [
            {
                fn: 'onContainerMyVideosInitialize',
                event: 'initialize'
            }
        ]
    },

    onContainerMyVideosInitialize: function(component, options) {
        Ext.getCmp("containerMyVideos").element.on({
            touchstart: function(e,node){


                //        variableContainerVideoPopularCanvas2=e.target;
                //        alert("feg");
                canvasContext2=e.target.getContext("2d");
                canvasContext2.moveTo(e.target.layerX,e.target.layerY);

                puntoTocadoAnteriorX2=e.event.layerX;
                puntoTocadoAnteriorY2=e.event.layerY;

            }
        });



        Ext.getCmp("containerMyVideos").element.on({
            touchmove: function(e,node){
                canvasContext2=e.target.getContext("2d");

                canvasContext2.strokeStyle='rgb(55,55,255)';

                canvasContext2.beginPath();

                canvasContext2.moveTo(puntoTocadoAnteriorX2,puntoTocadoAnteriorY2);

                canvasContext2.lineTo(e.event.layerX,e.event.layerY);
                canvasContext2.stroke();

                canvasContext2.closePath();

                puntoTocadoAnteriorX2=e.event.layerX;
                puntoTocadoAnteriorY2=e.event.layerY;
            }
        });
    }

});