/*
 * File: app/view/tabPanelPrincipal.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.tabPanelPrincipal', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.tabpanelprincipal',

    requires: [
        'MyApp.view.containerHome',
        'MyApp.view.containerProfile',
        'MyApp.view.containerMyVideos',
        'MyApp.view.containerPopular'
    ],

    config: {
        height: '80%',
        id: 'tabPanelMain',
        top: '20%',
        width: '100%',
        layout: {
            animation: 'fade',
            type: 'card'
        },
        tabBar: {
            docked: 'top',
            scrollable: 'horizontal',
            layout: {
                pack: 'center',
                type: 'hbox'
            }
        },
        items: [
            {
                xtype: 'containerhome',
                title: 'Home'
            },
            {
                xtype: 'containerprofile',
                title: 'My Profile'
            },
            {
                xtype: 'containermyvideos',
                title: 'My Videos'
            },
            {
                xtype: 'containerpopular',
                title: 'Popular'
            }
        ],
        listeners: [
            {
                fn: 'onTabPanelMainActiveItemChange',
                event: 'activeitemchange'
            },
            {
                fn: 'onTabPanelMainInitialize',
                event: 'initialize'
            }
        ]
    },

    onTabPanelMainActiveItemChange: function(container, value, oldValue, options) {





        if(value==Ext.getCmp("containerPopular")){
            //alert(document.getElementById("divDelCanvas").id);
            variableContainerVideoPopularCanvas=document.getElementById("canvas");
        }













        /*
        if(value.getId()=="containerPopular"){
        //--------------------------------------------------------------
        //    canvas=new Ext.draw.Canvas();
        //    value.add(canvas);

        //    canvas=document.getElementById("mycanvas");
        //    context=canvas.getContext('2d');
        //    cw=canvas.width;
        //    ch=canvas.height;
        //    context.strokeStyle='black';
        //    context.moveTo(0,0);
        //    context.lineTo(cw.ch);
        //    context.stroke();
        //    alert(canvas.height);



        value.element.on({
            touchstart: function(e,node){

                //    alert(e.target);
                //        alert(e.target.id);


                canvasContext=e.target.getContext("2d");
                //    alert("fwe;lwej");

                canvasContext.moveTo(e.target.layerX,e.target.layerY);

                puntoTocadoAnteriorX=e.event.layerX;
                puntoTocadoAnteriorY=e.event.layerY;



                //            canvasContext=e.target.getContext("2d");
                //
                //            canvasContext.fillText("X",10,75);
                //
                //
                //            canvasContext.moveTo(0,75);
                //            canvasContext.lineTo(500,75);
                //
                //            canvasContext.stroke();

            }
        });



        value.element.on({
            touchmove: function(e,node){
                //        alert("gato lococo");

                //    alert("fwef;j");
                //alert(e.target.id);





                canvasContext=e.target.getContext("2d");
                //    alert("fwe;lwej");

                //canvasContext.fillStyle='rgb(180,33,33)';

                canvasContext.strokeStyle='rgb(55,55,255)';

                canvasContext.beginPath();

                canvasContext.moveTo(puntoTocadoAnteriorX,puntoTocadoAnteriorY);

                canvasContext.lineTo(e.event.layerX,e.event.layerY);
                canvasContext.stroke();

                canvasContext.closePath();

                puntoTocadoAnteriorX=e.event.layerX;
                puntoTocadoAnteriorY=e.event.layerY;



                //Ext.getCmp("containerPopular").add(drawPixelPunto);

            }
        });
        */























        /*
        value.element.on({
        touchstart: function(e,self){
        //        alert("gato lococo");
        //canvas=value.getCanvasObject();

        context = value.getContext('2d');

        var drawPixelPunto=new Ext.draw.Component({
            items:[{
                type: 'circle',
                fill: '#79BB3F',
                radius: 3,
                x:e.event.layerX,
                y:e.event.layerY
            }]
        });
        Ext.getCmp("containerPopular").setItems([drawPixelPunto]);

    }
        });
        */
        //--------------------------------------------------------------
        //}
    },

    onTabPanelMainInitialize: function(component, options) {
        //this.setActiveItem(3);
    }

});