/*
 * File: app/view/BASURERO.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BASURERO', {
    extend: 'Ext.Container',

    config: {
        items: [
            {
                xtype: 'container',
                height: '100%',
                width: '100%',
                layout: {
                    type: 'fit'
                }
            },
            {
                xtype: 'button',
                text: 'MyButton'
            },
            {
                xtype: 'titlebar',
                docked: 'top'
            },
            {
                xtype: 'container',
                docked: 'top',
                height: '100%',
                id: 'containerImagenDirectorioCategorias',
                itemId: 'containerImagenDirectorioCategorias',
                width: '33%',
                layout: {
                    type: 'fit'
                }
            },
            {
                xtype: 'container',
                docked: 'left',
                height: '100%',
                id: 'containerImagenDirectorioAvanzado',
                itemId: 'containerImagenDirectorioAvanzado',
                left: '67%',
                top: '79%',
                width: '33%',
                layout: {
                    type: 'fit'
                }
            },
            {
                xtype: 'container',
                docked: 'left',
                height: '100%',
                id: 'containerImagenDirectorioMiLugar',
                itemId: 'containerImagenDirectorioMiLugar',
                width: '34%',
                layout: {
                    type: 'fit'
                }
            },
            {
                xtype: 'container',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'list',
                        height: '100%',
                        id: 'listaCategorias',
                        itemId: 'listaCategorias',
                        width: '100%',
                        scrollable: 'vertical',
                        inline: true,
                        itemTpl: [
                            '<div> Bla. </div>'
                        ],
                        store: 'storeCategorias'
                    }
                ]
            },
            {
                xtype: 'dataview',
                height: '100%',
                hidden: true,
                id: 'dataViewListaEmpresasEnSubcategoria',
                itemId: 'dataViewListaEmpresasEnSubcategoria',
                left: '5%',
                width: '95%',
                itemTpl: [
                    '<div>',
                    '    <tpl if="tipoPlan==1">',
                    '        <table border="0" width="300" height="250" style=\'table-layout:fixed\'>',
                    '    </tpl>',
                    '    <tpl if="tipoPlan==2">',
                    '        <table border="0" width="300" height="220" style=\'table-layout:fixed\'>',
                    '    </tpl>',
                    '    <tpl if="tipoPlan==3">',
                    '        <table border="0" width="300" height="160" style=\'table-layout:fixed\'>',
                    '    </tpl>',
                    '    <tpl if="tipoPlan==4">',
                    '        <table border="0" width="300" height="100" style=\'table-layout:fixed\'>',
                    '    </tpl>',
                    '    <tpl if="tipoPlan==5">',
                    '        <table border="0" width="300" height="100" style=\'table-layout:fixed\'>',
                    '    </tpl>',
                    '',
                    '        <col width="230">',
                    '        <col width="70">',
                    '        <tr>',
                    '            <td>',
                    '                <tpl if="tipoPlan==1">',
                    '                    <img src="{banner}" width="215" height="200" />',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==2">',
                    '                    <img src="{logo}" width="160" height="100" />',
                    '                    <p>{nombre}</p>',
                    '                    <p> Tel: {telefono} </p>',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==3">',
                    '                    <img src="{logo}" width="50" height="50" />',
                    '                    <b>',
                    '                        <p>{nombre}.',
                    '                        </p>',
                    '                        <p> Tel: {telefono}.',
                    '                        </p>',
                    '                    </b>',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==4">',
                    '                    <p>{nombre}.',
                    '                    </p>',
                    '                    <p>Tel: {telefono}.',
                    '                    </p>',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==5">',
                    '                    <p>{nombre}.',
                    '                    </p>',
                    '                    <p>Tel: {telefono}.',
                    '                    </p>',
                    '                </tpl>',
                    '            </td>',
                    '            <td align=right>',
                    '                <tpl if="tipoPlan==1">',
                    '                    <input type="button" id="botonParaLlamar" name="{nombre}" value="Llamar" style="padding:3px; color:green; height:60px; width: 100px;">',
                    '                    <input type="button" id="botonParaEnviarCorreo" name="{nombre}" value="E-mail" style="padding:3px; height: 35px; width: 100px;">',
                    '                    <input type="button" id="botonParaVerDescripcion" name="{nombre}" value="Descripcion" style="padding:3px; height: 35px; width: 100px;">',
                    '                    <input type="button" id="botonParaVerEnMapa" name="{nombre}" value="Mapa" style="padding:3px; height: 35px; width: 100px;">',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==2">',
                    '                    <input type="button" id="botonParaLlamar" name="{nombre}" value="Llamar" style="padding:3px; color:green; height:60px; width: 100px;">',
                    '                    <input type="button" id="botonParaEnviarCorreo" name="{nombre}" value="E-mail" style="padding:3px; height: 35px; width: 100px;">',
                    '                    <input type="button" id="botonParaVerDescripcion" name="{nombre}" value="Descripcion" style="padding:3px; height: 35px; width: 100px;">',
                    '                    <input type="button" id="botonParaVerEnMapa" name="{nombre}" value="Mapa" style="padding:3px; height: 35px; width: 100px;">',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==3">',
                    '                    <input type="button" id="botonParaVerDescripcion" name="{nombre}" value="Descripcion" style="padding:3px; height: 35px; width: 100px;">',
                    '                    <input type="button" id="botonParaVerEnMapa" name="{nombre}" value="Mapa" style="padding:3px; height: 35px; width: 100px;">',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==4">',
                    '                    <input type="button" id="botonParaVerDescripcion" name="{nombre}" value="Descripcion" style="padding:3px; height: 35px; width: 100px;">',
                    '                    <input type="button" id="botonParaVerEnMapa" name="{nombre}" value="Mapa" style="padding:3px; height: 35px; width: 100px;">',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==5">',
                    '                    <input type="button" id="botonParaVerDescripcion" name="{nombre}" value="Descripcion" style="padding:3px; height: 35px; width: 100px;">',
                    '                    <input type="button" id="botonParaVerEnMapa" name="{nombre}" value="Mapa" style="padding:3px; height: 35px; width: 100px;">',
                    '                </tpl>',
                    '',
                    '            </td>',
                    '        </tr>',
                    '    </table>',
                    '</div>',
                    '',
                    '',
                    ''
                ],
                store: 'storeListaEmpresasEnSubcategoria'
            },
            {
                xtype: 'list',
                id: 'listaDescripcionEmpresa',
                itemTpl: [
                    '<img src="{imagenGran}" width="93%" height="220" />'
                ],
                store: 'storeDescripcionEventos',
                disableSelection: true
            },
            {
                xtype: 'list',
                height: '100%',
                id: 'listaViewListaDescripcionEmpresa',
                itemId: 'listaViewListaDescripcionEmpresa',
                left: '0%',
                width: '100%',
                itemTpl: [
                    '<div>',
                    '    <tpl if="tipoPlan==1">',
                    '        <table border="0"  height="260" style=\'table-layout:fixed; width: 100%;\'>',
                    '    </tpl>',
                    '    <tpl if="tipoPlan==2">',
                    '        <table border="0" height="190" style=\'table-layout:fixed; width: 100%;\'>',
                    '    </tpl>',
                    '    <tpl if="tipoPlan==3">',
                    '        <table border="0" height="130" style=\'table-layout:fixed; width: 100%;\'>',
                    '    </tpl>',
                    '    <tpl if="tipoPlan==4">',
                    '        <table border="0" height="100" style=\'table-layout:fixed; width: 100%;\'>',
                    '    </tpl>',
                    '    <tpl if="tipoPlan==5">',
                    '        <table border="0" height="100" style=\'table-layout:fixed; width: 100%;\'>',
                    '    </tpl>',
                    '',
                    '        <col width="70%">',
                    '        <col width="30%">',
                    '        <tr>',
                    '            <td>',
                    '                <tpl if="tipoPlan==1">',
                    '                    <img src="{banner}" width="93%" height="220" />',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==2">',
                    '                    <img src="{logo}" width="60%" height="100" />',
                    '                    <i>',
                    '                    <p style="font-family:texgyrechorus;color:black;">{nombre}</p>',
                    '                    <p style="font-family:texgyrechorus;color:black;"> Tel: {telefono} </p>',
                    '                    </i>',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==3">',
                    '                    <img src="{logo}" width="20%" height="50" />',
                    '                    <b>',
                    '                        <p>{nombre}.',
                    '                        </p>',
                    '                        <p> Tel: {telefono}.',
                    '                        </p>',
                    '                    </b>',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==4">',
                    '                    <p>{nombre}.',
                    '                    </p>',
                    '                    <p>Tel: {telefono}.',
                    '                    </p>',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==5">',
                    '                    <p>{nombre}.',
                    '                    </p>',
                    '                    <p>Tel: {telefono}.',
                    '                    </p>',
                    '                </tpl>',
                    '            </td>',
                    '            <td align=right>',
                    '                <tpl if="tipoPlan==1">',
                    '                    <input type="button" id="botonParaLlamar" name="{nombre}" value="Llamar" style="font-family: texgyrechorus; background-color:#A9F5BC; padding:3px; color:green; height:60px; width: 100%;">',
                    '                    <input type="button" id="botonParaEnviarCorreo" name="{nombre}" value="E-mail" style="font-family: texgyrechorus; padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                    <input type="button" id="botonParaVerDescripcion" name="{nombre}" value="Descripcion" style="font-family: texgyrechorus; padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                    <input type="button" id="botonParaVerEnMapa" name="{nombre}" value="Mapa" style="font-family: texgyrechorus; padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==2">',
                    '                    <input type="button" id="botonParaEnviarCorreo" name="{nombre}" value="E-mail" style="padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                    <input type="button" id="botonParaVerDescripcion" name="{nombre}" value="Descripcion" style="padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                    <input type="button" id="botonParaVerEnMapa" name="{nombre}" value="Mapa" style="padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==3">',
                    '                    <input type="button" id="botonParaVerDescripcion" name="{nombre}" value="Descripcion" style="padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                    <input type="button" id="botonParaVerEnMapa" name="{nombre}" value="Mapa" style="padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==4">',
                    '                    <input type="button" id="botonParaVerDescripcion" name="{nombre}" value="Descripcion" style="padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                    <input type="button" id="botonParaVerEnMapa" name="{nombre}" value="Mapa" style="padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                </tpl>',
                    '                <tpl if="tipoPlan==5">',
                    '                    <input type="button" id="botonParaVerDescripcion" name="{nombre}" value="Descripcion" style="padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                    <input type="button" id="botonParaVerEnMapa" name="{nombre}" value="Mapa" style="padding:3px; color: gray; height: 35px; width: 100%;">',
                    '                </tpl>',
                    '',
                    '            </td>',
                    '        </tr>',
                    '    </table>',
                    '</div>',
                    ''
                ],
                loadingText: 'Cargando...',
                store: 'storeEmpresaEnDescripcionEmpresa',
                disableSelection: true
            },
            {
                xtype: 'container',
                height: '100%',
                id: 'containerBotonesDescripcionEmpresa',
                left: '75%',
                width: '25%',
                layout: {
                    type: 'vbox'
                },
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'button',
                        height: '15%',
                        id: 'botonLlamarContainerBotonesDescEmpresa',
                        left: '10%',
                        top: '2.5%',
                        ui: 'action',
                        width: '80%',
                        iconCls: 'reply',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        height: '15%',
                        id: 'botonMapaContainerBotonesDescEmpresa',
                        left: '10%',
                        top: '22.5%',
                        ui: 'confirm',
                        width: '80%',
                        iconCls: 'locate',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        height: '15%',
                        id: 'botonEnlaceWebContainerBotonesDescEmpresa',
                        left: '10%',
                        top: '42.5%',
                        ui: 'decline',
                        width: '80%',
                        iconCls: 'info',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        height: '15%',
                        id: 'botonFacebookContainerBotonesDescEmpresa',
                        left: '10%',
                        top: '62.5%',
                        ui: 'action',
                        width: '80%',
                        text: 'f'
                    },
                    {
                        xtype: 'button',
                        height: '15%',
                        id: 'botonDidiRapidosContainerBotonesDescEmpresa',
                        left: '10%',
                        top: '82.5%',
                        ui: 'confirm',
                        width: '80%',
                        iconCls: 'compose',
                        iconMask: true
                    }
                ]
            },
            {
                xtype: 'container',
                height: '100%',
                id: 'containerBotonesDescripcionEmpresa',
                left: '0%',
                width: '25%',
                layout: {
                    type: 'vbox'
                },
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'button',
                        height: '15%',
                        id: 'botonLlamarContainerBotonesDescEmpresa',
                        left: '10%',
                        top: '2.5%',
                        ui: 'action',
                        width: '80%',
                        iconCls: 'reply',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        height: '15%',
                        id: 'botonMapaContainerBotonesDescEmpresa',
                        left: '10%',
                        top: '22.5%',
                        ui: 'confirm',
                        width: '80%',
                        iconCls: 'locate',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        height: '15%',
                        id: 'botonEnlaceWebContainerBotonesDescEmpresa',
                        left: '10%',
                        top: '42.5%',
                        ui: 'decline',
                        width: '80%',
                        iconCls: 'info',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        height: '15%',
                        id: 'botonFacebookContainerBotonesDescEmpresa',
                        left: '10%',
                        top: '62.5%',
                        ui: 'action',
                        width: '80%',
                        text: 'f'
                    },
                    {
                        xtype: 'button',
                        height: '15%',
                        id: 'botonDidiRapidosContainerBotonesDescEmpresa',
                        left: '10%',
                        top: '82.5%',
                        ui: 'confirm',
                        width: '80%',
                        iconCls: 'compose',
                        iconMask: true
                    }
                ]
            },
            {
                xtype: 'searchfield',
                id: 'searchFieldToolbarContainerMapa',
                left: '50%',
                width: '40%',
                placeHolder: 'Buscar'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                height: '10%',
                id: 'toolbarInferiorContainerMapa',
                style: 'background: #3E3737',
                items: [
                    {
                        xtype: 'selectfield',
                        id: 'selectFieldMapaPrincipal',
                        itemId: 'selectFieldMapaPrincipal',
                        width: '65%',
                        label: 'Categoría:',
                        labelWidth: '40%',
                        displayField: 'nombre',
                        store: 'storeSelectFieldContainerMapa',
                        valueField: '{nombre}'
                    },
                    {
                        xtype: 'button',
                        height: '80%',
                        id: 'botonFavoritosMapa',
                        right: '5%',
                        top: '10%',
                        ui: 'confirm',
                        width: '15%',
                        iconCls: 'favorites',
                        iconMask: true
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                height: '10%',
                id: 'toolbarContainerMapa',
                style: 'background: #3E3737',
                items: [
                    {
                        xtype: 'image',
                        height: '100%%',
                        html: '<img src="http://www.didicr.com/imagenes/Logo_DD.png" width="100%" height="100%">',
                        id: 'imagenToolbarContainerMapa',
                        width: '40%'
                    }
                ]
            },
            {
                xtype: 'button',
                height: '10%',
                id: 'botonFiltroMapaContainerEventos',
                left: '30%',
                top: '80%',
                ui: 'confirm-round',
                width: '40%',
                text: 'Filtro'
            },
            {
                xtype: 'checkboxfield',
                id: 'checkBoxEscogenciaEntreMapasEventos',
                itemId: 'mycheckbox9',
                label: 'Por eventos',
                labelWidth: '60%'
            },
            {
                xtype: 'checkboxfield',
                id: 'checkBoxEscogenciaEntreMapasEmpresas',
                itemId: 'mycheckbox10',
                label: 'Por empresa',
                labelWidth: '60%'
            },
            {
                xtype: 'button',
                handler: function(button, event) {


                    Ext.getCmp("panelEscogenciaEntreMapaEventosOMapaEmpresas").setHidden(1);


                    if(Ext.getCmp("checkBoxEscogenciaEntreMapasEmpresas").getChecked()===true){
                        //
                    }
                    else{
                        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerEventos"));
                        Ext.getCmp("containerPrincipalEventos").setHidden(1);
                        Ext.getCmp("containerMapaEventos").setHidden(0);

                        //Ext.getCmp("dataViewDidiMapaEventos").setHidden(1);
                    }


                },
                docked: 'bottom',
                id: 'botonListoPanelEscogenciaEntreMapas',
                ui: 'confirm-round',
                text: 'Listo'
            },
            {
                xtype: 'dataview',
                height: '20%',
                id: 'dataViewDidiMapaEventos',
                top: '80%',
                width: '100%',
                layout: {
                    type: 'hbox'
                },
                scrollable: 'horizontal',
                inline: {
                    wrap: false
                },
                itemTpl: [
                    '<div> cosa  </div>',
                    '',
                    ''
                ],
                loadingText: 'Cargando...',
                store: 'storeCategorias'
            },
            {
                xtype: 'datepickerfield',
                border: '3%',
                height: '10%',
                id: 'dateFieldHoraReservacionRestaurante',
                itemId: 'dateFieldHoraReservacionRestaurante',
                top: '10%',
                width: '100%',
                label: 'Hora',
                labelWidth: '45%',
                placeHolder: 'mm/dd/yyyy',
                picker: {
                    height: '30%',
                    slotOrder: [
                        'year',
                        'month',
                        'day'
                    ],
                    yearFrom: 1,
                    yearText: 'Horas',
                    yearTo: 24
                }
            },
            {
                xtype: 'container',
                height: '16%',
                hidden: true,
                id: 'containerBotonListoEscogenciaOcasion',
                itemId: 'containerBotonListoEscogenciaOcasion',
                top: '85%',
                width: '100%',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp("panelElegirOcasionReservacionRestaurante").setHidden(1);
                        },
                        id: 'botonListoEscogenciaOcasion',
                        itemId: 'botonListoEscogenciaOcasion',
                        ui: 'confirm-round',
                        text: 'Listo'
                    }
                ]
            },
            {
                xtype: 'container',
                height: '35%',
                html: '<img src="http://3.bp.blogspot.com/_3Z__e0t7y7g/ScHlKzFswUI/AAAAAAAAABE/THYGpkp2PHM/S958-R/Logo+Pana+Bar1.jpg" height=\'100%\' width=\'100%\'>',
                id: 'containerImagenPrincipalModuloReservaciones',
                top: '65%',
                width: '100%'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    //Se pasa al view de calendario
                    Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerCalendarioEventos"));
                },
                height: '7%',
                id: 'botonCalendarioContainerEventos',
                left: '52.5%',
                top: '53%',
                ui: 'decline-round',
                width: '45%',
                text: 'Calendario'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                height: '10%',
                id: 'toolbarDelContainerPerfilDeUsuario',
                style: 'background: #3E3737',
                title: 'PERFIL'
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        id: 'PrincipalAAA',
                        title: 'PrincipalAAA',
                        items: [
                            {
                                xtype: 'button',
                                handler: function(button, event) {
                                    if (Ext.getCmp('containerDelPerfilUsuario').isHidden()) {
                                        Ext.getCmp('containerDelPerfilUsuario').show();   
                                    }


                                    var main = Ext.get('inicioAAA');


                                    if (main.hasCls('out')) {
                                        main.removeCls('out');
                                        main.addCls('in'); 
                                        button.setText('Open');
                                    } else {
                                        main.removeCls('in');    
                                        main.addCls('out');    
                                        button.setText('Close');         
                                    }
                                },
                                id: 'botonPrincipalAAA',
                                text: 'Open'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        html: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque vitae sagittis ipsum. Nam eros orci, iaculis a cursus eget, eleifend id sapien. In hac habitasse platea dictumst. Aliquam sagittis adipiscing aliquet. Etiam nec mi nisi, vel convallis nisi. Nunc congue ultrices risus, at rutrum est aliquet in. Pellentesque purus eros, scelerisque vehicula porttitor vel, facilisis at mi. Quisque vestibulum, neque vitae mattis dignissim, dui nisi lacinia quam, et faucibus elit lacus eu massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porttitor, elit ac luctus dignissim, justo massa eleifend metus, id consequat est diam a lorem. Maecenas et viverra dolor. Proin sed eros id arcu vehicula tincidunt eu a diam. Donec eu quam ut velit iaculis aliquam sed a neque. Sed vel sapien dui, vel tristique nulla. Maecenas a lectus urna.  Quisque porta rutrum posuere. Vestibulum fermentum convallis erat, vel eleifend nisl viverra sed. Duis orci nulla, vestibulum vitae euismod vitae, sodales id turpis. In lobortis scelerisque lacinia. Quisque ac nulla ultricies diam accumsan tempus. Morbi non odio mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur pellentesque accumsan sem, non porttitor ipsum rutrum eu. Vivamus vel metus metus. Mauris mollis ullamcorper porttitor. Vestibulum egestas eleifend augue posuere adipiscing. Aenean tempor tempus eros, mollis feugiat est cursus mattis.</p>\',                         id: \'item-example',
                        id: 'container1AAA',
                        padding: '0.5em',
                        scrollable: true
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'containerPickersReservaRestaurante',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        height: '10%',
                        id: 'toolbarContainerPickersReservaRestaurante',
                        style: 'background: #3E3737',
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%%',
                                html: '<img src="http://www.didicr.com/imagenes/Logo_DD.png" width="100%" height="100%">',
                                id: 'imagenToolbarContainerPickersReservaRestaurante',
                                itemId: 'myimage18',
                                width: '40%'
                            },
                            {
                                xtype: 'button',
                                handler: function(button, event) {
                                    //Se devuleve hacia containerInicio, ya que se esta en busqueda
                                    Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp(viewDelQuePasoHaciaContainerPickerReservaRestaurante));

                                    //alert(Ext.getCmp("picker1ReservaRestaurante").getValue()['MyPickerSlot1']);
                                    //picker2ReservaRestaurante
                                    //alert("erf");
                                    Ext.getCmp("selectFieldHoraReservaRestaurante").setPlaceHolder(Ext.getCmp("picker1ReservaRestaurante").getValue()['MyPickerSlot1']+":"+Ext.getCmp("picker2ReservaRestaurante").getValue()['MyPickerSlot2']+" "+Ext.getCmp("picker3ReservaRestaurante").getValue()['MyPickerSlot3']);

                                    //{"text":"feisimo","value":1}
                                    //Ext.getCmp("selectFieldHoraReservaRestaurante").setData({"text": "fieo","value": 0});


                                },
                                height: '40%',
                                id: 'botonAtrasContainerPickersReservaRestaurante',
                                right: '2%',
                                top: '10%',
                                ui: 'action-round',
                                width: '20%',
                                text: 'Atrás'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    //Se quitar el tabBar
                    Ext.getCmp("tabPanelPrincipal").getTabBar().setHidden(1);
                    //Se esta pasando desde el containerEventos hacia el mapaEventos, por lo que
                    //hay que cargar el store de categorias para el dataView de la parte inferior
                    viewDelQuePasoHaciaMapaEventos="containerEventos";
                    Ext.getStore("storeCategoriasEventos").load();
                    //Se muestra dicho dataView
                    Ext.getCmp("dataViewDidiMapaEventos").setHidden(0);
                    //Se borran los markers en ese mapaEventos, para poner los nuevos
                    while(markersMapaEventos[0]){
                        markersMapaEventos.pop().setMap(null);
                    }
                    //Finalmente, se pasa a ese view que contiene al mapa de Eventos
                    Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerMapaEventos"));
                },
                height: '7%',
                id: 'botonCercaniaContainerEventos',
                left: '27.5%',
                top: '53%',
                ui: 'confirm-round',
                width: '45%',
                text: 'Cercanía'
            },
            {
                xtype: 'list',
                hidden: true,
                id: 'listaFavoritosEmpresasPerfilUsuario',
                itemId: 'mylist10',
                itemTpl: [
                    '<div>{nombre}</div>'
                ],
                store: 'storeExtraccionFavoritasEmpresasPerfilUsuario',
                grouped: true
            },
            {
                xtype: 'container',
                docked: 'top',
                height: '7%',
                html: '<img src="http://www.didicr.com/imagenes/rapidos/tituloDidiRapidos.png" height="100%" width="100%">',
                id: 'containerTituloDidiRapidos',
                itemId: 'containerTituloDidiRapidos',
                width: '100%'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    if(Ext.getCmp("carouselPromocionEmpresa").getActiveIndex()<(Ext.getCmp("carouselPromocionEmpresa").getInnerItems().length-1)){
                        Ext.getCmp("carouselPromocionEmpresa").next();
                    }

                },
                height: '100%',
                hidden: true,
                id: 'botonMoverDerechaCarouselPromocionEmpresa',
                right: '0%',
                width: '10%',
                iconCls: 'arrow_right',
                iconMask: true
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    //alert(Ext.getCmp("carouselPromocionEmpresa").getActiveIndex());
                    //alert(Ext.getCmp("carouselPromocionEmpresa").getInnerItems().length);






                    /*
                    if(Ext.getCmp("carouselPromocionEmpresa").getActiveItem()>0){

                    }






                    //Funcion para ir cambiando las imagenes en eventos
                    var funcionCambioEstadoCarousel = function() {
                        var task = Ext.create('Ext.util.DelayedTask', function() {
                            //console.log('hi');
                            Ext.getCmp("carouselEventos").next();
                            if(Ext.getCmp("carouselEventos").getActiveIndex()==Ext.getCmp("carouselEventos").getItems().length-2){Ext.getCmp("carouselEventos").setActiveItem(0);}
                            funcionCambioEstadoCarousel.call(this);
                        }, this);
                        task.delay(5000);
                    };
                    //Esta es la funcion que hace que cambien las imagenes en el carousel Inicio
                    funcionCambioEstadoCarousel();
                    */
                },
                id: 'botonMoverIzquierdaCarouselPromocionEmpresa',
                style: 'background-color: transparent;',
                width: '10%',
                iconCls: 'arrow_left',
                iconMask: true
            },
            {
                xtype: 'image',
                height: '15%',
                html: '<img src="http://www.didicr.com/imagenes/arrow_right.png" width="100%" height="100%">',
                id: 'imagenMoverDerechaCarouselPromocionEmpresa',
                itemId: 'myimage44',
                right: 0,
                top: '40%',
                width: '8%'
            },
            {
                xtype: 'picker',
                height: '100%',
                id: 'picker3ReservaRestaurante',
                left: '67%',
                top: '0%',
                width: '33%',
                modal: false,
                doneButton: {
                    hidden: true,
                    id: 'done3'
                },
                cancelButton: {
                    hidden: true,
                    id: 'cancel3'
                },
                slots: [
                    {
                        xtype: 'pickerslot',
                        id: 'pickerSlotAMPMEscogenciaHoraDidiReserva',
                        data: [
                            {
                                text: 'a.m.',
                                value: 'a.m.'
                            },
                            {
                                text: 'p.m.',
                                value: 'p.m.'
                            },
                            {
                                text: '',
                                value: ''
                            }
                        ],
                        name: 'MyPickerSlot3',
                        title: 'MyPickerSlot3'
                    }
                ]
            },
            {
                xtype: 'image',
                docked: 'left',
                height: '92%',
                html: '<img src="http://www.didicr.com/imagenes/directorio/categoria.png" height="100%" width="100%">',
                id: 'imagenDirectorioCategorias',
                itemId: 'imagenDirectorioCategorias',
                left: '3%',
                maxHeight: 196,
                maxWidth: 196,
                top: '4%',
                width: '29%'
            },
            {
                xtype: 'image',
                centered: true,
                height: '92%',
                html: '<center><img src="http://www.didicr.com/imagenes/directorio/miLugar.png" height="100%" width="100%"></center>',
                id: 'imagenDirectorioMiLugar',
                itemId: 'imagenDirectorioMiLugar',
                left: '35%',
                maxHeight: 196,
                maxWidth: 196,
                top: '4%',
                width: '30%'
            },
            {
                xtype: 'image',
                height: '92%',
                html: '<img src="http://www.didicr.com/imagenes/directorio/avanzado.png" height="100%" width="100%">',
                id: 'imagenDirectorioAvanzado',
                itemId: 'imagenDirectorioAvanzado',
                maxHeight: 196,
                maxWidth: 196,
                right: '3%',
                top: '4%',
                width: '29%'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    //Esta linea es para cambiar al tab anterior
                    //Ext.getCmp("tabPanelPrincipal").setActiveItem(viewDelQuePasoHaciaContainerNotificacionesPerfilUsuario);



                    Ext.getCmp('containerDelPerfilUsuario').setHidden(0);


                    var main = Ext.get('containerParaTabPanelPrincipal');


                    if (main.hasCls('out')) {
                        main.removeCls('out');
                        main.addCls('in'); 
                        //button.setText('Usuario');
                    } else {
                        main.removeCls('in');    
                        main.addCls('out');    
                        //button.setText('Usuario');         
                    }



                },
                baseCls: 'botonAtras',
                height: '80%',
                id: 'botonAtrasContainerNotificacionesPerfilUsuario2',
                right: '2%',
                top: '10%',
                ui: 'action-round',
                width: '15%'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    //Esta linea es para cambiar al tab anterior
                    //Ext.getCmp("tabPanelPrincipal").setActiveItem(viewDelQuePasoHaciaContainerReservasPerfilUsuario);




                    Ext.getCmp('containerDelPerfilUsuario').setHidden(0);


                    var main = Ext.get('containerParaTabPanelPrincipal');


                    if (main.hasCls('out')) {
                        main.removeCls('out');
                        main.addCls('in'); 
                        //button.setText('Usuario');
                    } else {
                        main.removeCls('in');    
                        main.addCls('out');    
                        //button.setText('Usuario');         
                    }



                },
                baseCls: 'botonAtras',
                height: '80%',
                id: 'botonAtrasContainerReservasPerfilUsuario2',
                right: '2%',
                top: '10%',
                ui: 'action-round',
                width: '15%'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    //Esta linea es para cambiar al tab anterior
                    //Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));



                    Ext.getCmp('containerDelPerfilUsuario').setHidden(0);


                    var main = Ext.get('containerParaTabPanelPrincipal');


                    if (main.hasCls('out')) {
                        main.removeCls('out');
                        main.addCls('in'); 
                        //button.setText('Usuario');
                    } else {
                        main.removeCls('in');    
                        main.addCls('out');    
                        //button.setText('Usuario');         
                    }



                },
                baseCls: 'botonAtras',
                height: '80%',
                id: 'botonAtrasContainerFavoritosEmpresasPerfilUsuario2',
                right: '2%',
                top: '10%',
                ui: 'action-round',
                width: '15%'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    //Esta linea es para cambiar al tab anterior
                    //Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));




                    Ext.getCmp('containerDelPerfilUsuario').setHidden(0);


                    var main = Ext.get('containerParaTabPanelPrincipal');


                    if (main.hasCls('out')) {
                        main.removeCls('out');
                        main.addCls('in'); 
                        //button.setText('Usuario');
                    } else {
                        main.removeCls('in');    
                        main.addCls('out');    
                        //button.setText('Usuario');         
                    }


                },
                baseCls: 'botonAtras',
                height: '80%',
                id: 'botonAtrasContainerFavoritosEventosPerfilUsuario2',
                right: '2%',
                top: '10%',
                ui: 'action-round',
                width: '15%'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    //Esta linea es para cambiar al tab anterior
                    //Ext.getCmp("tabPanelPrincipal").setActiveItem(viewDelQuePasoHaciaContainerPerfilPerfilUsuario);



                    Ext.getCmp('containerDelPerfilUsuario').setHidden(0);


                    var main = Ext.get('containerParaTabPanelPrincipal');


                    if (main.hasCls('out')) {
                        main.removeCls('out');
                        main.addCls('in'); 
                        //button.setText('Usuario');
                    } else {
                        main.removeCls('in');    
                        main.addCls('out');    
                        //button.setText('Usuario');         
                    }



                },
                baseCls: 'botonAtras',
                height: '80%',
                id: 'botonAtrasContainerPerfilPerfilUsuario2',
                right: '2%',
                top: '10%',
                ui: 'action-round',
                width: '15%'
            },
            {
                xtype: 'image',
                height: '7%',
                html: '<img src="http://www.didicr.com/imagenes/cssEvento/DD_busqueda_cercania.png" height="100%" width="100%">',
                id: 'imagenCercaniaContainerEventos',
                itemId: 'myimage41',
                left: '27.5%',
                top: '54%',
                width: '45%'
            },
            {
                xtype: 'image',
                height: '45%',
                id: 'imagenCatEventos1',
                itemId: 'imagenMusicaEventos',
                left: '2.5%',
                top: '5%',
                width: '20%'
            },
            {
                xtype: 'image',
                height: '45%',
                id: 'imagenCatEventos2',
                itemId: 'imagenMayores18Eventos',
                left: '27.5%',
                top: '5%',
                width: '20%'
            },
            {
                xtype: 'image',
                height: '45%',
                id: 'imagenCatEventos3',
                itemId: 'imageComidasEventos',
                left: '52.5%',
                top: '5%',
                width: '20%'
            },
            {
                xtype: 'image',
                height: '45%',
                id: 'imagenCatEventos4',
                left: '77.5%',
                top: '5%',
                width: '20%'
            },
            {
                xtype: 'image',
                height: '45%',
                id: 'imagenCatEventos5',
                left: '2.5%',
                top: '52.5%',
                width: '20%'
            },
            {
                xtype: 'image',
                height: '45%',
                id: 'imagenCatEventos6',
                left: '27.5%',
                top: '52.5%',
                width: '20%'
            },
            {
                xtype: 'image',
                height: '45%',
                id: 'imagenCatEventos7',
                left: '52.5%',
                top: '52.5%',
                width: '20%'
            },
            {
                xtype: 'image',
                height: '45%',
                id: 'imagenCatEventos8',
                left: '77.5%',
                top: '52.5%',
                width: '20%'
            },
            {
                xtype: 'button',
                handler: function(button, event) {

                },
                height: '7%',
                left: '80%',
                top: '30%',
                ui: 'decline-round',
                width: '20%',
                text: 'Acc'
            }
        ],
        listeners: [
            {
                fn: 'onMyselectfieldChange',
                event: 'change',
                delegate: '#selectFieldMapaPrincipal'
            },
            {
                fn: 'onCheckBoxEscogenciaEntreMapasEventosChange',
                event: 'change',
                delegate: '#checkBoxEscogenciaEntreMapasEventos'
            },
            {
                fn: 'onCheckBoxEscogenciaEntreMapasEmpresasChange',
                event: 'change',
                delegate: '#checkBoxEscogenciaEntreMapasEmpresas'
            },
            {
                fn: 'onImagenToolbarContainerGeolocalizacionTap11',
                event: 'tap',
                delegate: '#imagenToolbarContainerPickersReservaRestaurante'
            },
            {
                fn: 'onListaFavoritosEventosPerfilUsuarioItemSwipe1',
                event: 'itemswipe',
                delegate: '#listaFavoritosEmpresasPerfilUsuario'
            },
            {
                fn: 'onListaFavoritosEmpresasPerfilUsuarioItemTap',
                event: 'itemtap',
                delegate: '#listaFavoritosEmpresasPerfilUsuario'
            },
            {
                fn: 'onImagenMoverDerechaCarouselPromocionEmpresaTap',
                event: 'tap',
                delegate: '#imagenMoverDerechaCarouselPromocionEmpresa'
            },
            {
                fn: 'onImagenDirectorioCategoriasTap',
                event: 'tap',
                delegate: '#imagenDirectorioCategorias'
            },
            {
                fn: 'onImagenDirectorioMiLugarTap',
                event: 'tap',
                delegate: '#imagenDirectorioMiLugar'
            },
            {
                fn: 'onImagenDirectorioAvanzadoTap',
                event: 'tap',
                delegate: '#imagenDirectorioAvanzado'
            },
            {
                fn: 'onImagenCercaniaContainerEventosTap',
                event: 'tap',
                delegate: '#imagenCercaniaContainerEventos'
            }
        ]
    },

    onMyselectfieldChange: function(selectfield, newValue, oldValue, options) {
        Ext.getStore("storeSelectFieldContainerMapa").getProxy().setExtraParam('sub', 'todas');
        Ext.getStore("storeSelectFieldContainerMapa").getProxy().setExtraParam('cat', selectFieldMapa.getRecord().get("nombre"));
        Ext.getStore("storeSelectFieldContainerMapa").load();

    },

    onCheckBoxEscogenciaEntreMapasEventosChange: function(checkboxfield, newValue, oldValue, eOpts) {
        //Este codigo permite tener activo solamente uno de los dos checkbox
        if(Ext.getCmp("checkBoxEscogenciaEntreMapasEventos").getChecked()===true){
            Ext.getCmp("checkBoxEscogenciaEntreMapasEmpresas").reset();
        }
    },

    onCheckBoxEscogenciaEntreMapasEmpresasChange: function(checkboxfield, newValue, oldValue, eOpts) {
        //Este codigo permite tener activo solamente uno de los dos checkbox
        if(Ext.getCmp("checkBoxEscogenciaEntreMapasEmpresas").getChecked()===true){
            Ext.getCmp("checkBoxEscogenciaEntreMapasEventos").reset();
        }
    },

    onImagenToolbarContainerGeolocalizacionTap11: function(img, e, options) {
        //Todo logo de Didi redirige hacia containerInicio
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));
    },

    onListaFavoritosEventosPerfilUsuarioItemSwipe1: function(dataview, index, target, record, e, options) {
        funcionEliminadoEmpresasFavoritasPerfilUsuario=function(buttonId){
            if(buttonId=="no"){
                //
            }
            else{
                Ext.getStore("storeEnvioAgregadoFavoritosEmpresasPerfilUsuario").getProxy().setUrl("http://www.didicr.com/php/didiFavorito/borraEmpresaFavoritaPorIdEmpresaFavorita.php");
                Ext.getStore("storeEnvioAgregadoFavoritosEmpresasPerfilUsuario").getProxy().setExtraParam('idUsuarioEventoFavoritoParam',record.get("idUsuarioEmpresaFavorita"));
                alert(record.get("idUsuarioEmpresaFavorita"));
                Ext.getStore("storeEnvioAgregadoFavoritosEmpresasPerfilUsuario").load();
                alert("fdet");
                //        Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").getProxy().setExtraParam('idUsuarioParam',3);
                Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").load();
                Ext.Msg.alert('Aviso', 'Empresa eliminada exitosamente.', Ext.emptyFn);
            }
            //
        };

        Ext.Msg.confirm("Aviso", "Desea eliminar esta empresa de sus favoritas?", funcionEliminadoEmpresasFavoritasPerfilUsuario);







    },

    onListaFavoritosEmpresasPerfilUsuarioItemTap: function(dataview, index, target, record, e, options) {

    },

    onImagenMoverDerechaCarouselPromocionEmpresaTap: function(img, e, options) {
        alert("faweghj");

        if(Ext.getCmp("carouselPromocionEmpresa").getActiveIndex()<(Ext.getCmp("carouselPromocionEmpresa").getInnerItems().length-1)){
            Ext.getCmp("carouselPromocionEmpresa").next();
        }

    },

    onImagenDirectorioCategoriasTap: function(img, e, options) {
        //Con este if se carga el store que contiene a las existentes Categorias
        if(Ext.getStore("storeCategorias").isLoaded()===false){
            Ext.getStore("storeCategorias").load();
        }
        //Ademas, hay que pasar al view donde estan todas las categorias
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerCategorias"));
    },

    onImagenDirectorioMiLugarTap: function(img, e, options) {
        //Hay que pasar al view correspondiente de Geolocalizacion, que dara una
        //busqueda por Listado y por Mapa
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerFormularioGeolocalizacion"));
    },

    onImagenDirectorioAvanzadoTap: function(img, e, options) {
        //Se pasa al view de directorio Avanzado para hacer una busqueda por subcat, 
        //cat, canton, provincia y palabra clave
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerBusquedaAvanzada"));
    },

    onImagenCercaniaContainerEventosTap: function(img, e, options) {
        Ext.getCmp("containerPrincipalEventos").setMasked({xtype: 'loadmask', message: 'Espere por favor...'});

        //Se quitar el tabBar
        Ext.getCmp("tabPanelPrincipal").getTabBar().setHidden(1);
        //Se esta pasando desde el containerEventos hacia el mapaEventos, por lo que
        //hay que cargar el store de categorias para el dataView de la parte inferior
        viewDelQuePasoHaciaMapaEventos="containerEventos";
        Ext.getStore("storeCategoriasEventos").load();
        //Se muestra dicho dataView
        Ext.getCmp("dataViewDidiMapaEventos").setHidden(0);
        //Se borran los markers en ese mapaEventos, para poner los nuevos
        while(markersMapaEventos[0]){
            markersMapaEventos.pop().setMap(null);
        }
        //Finalmente, se pasa a ese view que contiene al mapa de Eventos
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerMapaEventos"));
    }

});