/*
 * File: app/view/containerMapaEventos.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerMapaEventos', {
    extend: 'Ext.Container',
    alias: 'widget.containermapaeventos',

    requires: [
        'MyApp.view.mapaCercaniaEventos'
    ],

    config: {
        hidden: true,
        id: 'containerMapaEventos',
        itemId: 'containerMapaEventos',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'mapacercaniaeventos'
            },
            {
                xtype: 'toolbar',
                border: 0,
                docked: 'top',
                height: '10%',
                id: 'toolbarMapaContainerMapa',
                style: 'background: #3E3737',
                items: [
                    {
                        xtype: 'image',
                        centered: true,
                        height: '100%',
                        html: '<img src="./resources/logo/Logo_DD.png" width="100%" height="100%">',
                        id: 'imagenLogoDidiMapaEventos',
                        itemId: 'myimage26',
                        left: '30%',
                        width: '40%'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //Al salir del mapa, hay que hacer visible el tabBar nuevamente
                            Ext.getCmp("tabPanelPrincipal").getTabBar().setHidden(0);
                            //Se retorna hacia el view desde el cual se ingreso a este mapa
                            Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp(viewDelQuePasoHaciaMapaEventos));


                            directionsDisplay.setMap(null);


                        },
                        baseCls: 'botonAtras',
                        height: '80%',
                        id: 'botonAtrasDidiMapaEventos',
                        right: '2%',
                        top: '10%',
                        ui: 'action-round',
                        width: '15%'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //Con este codigo se puede devolver hacia la current Location, es decir,
                            //se puede centrar el mapa en la posicion de uno
                            if (navigator.geolocation) {
                                navigator.geolocation.getCurrentPosition(
                                function(position){
                                    //Se crea un objeto de posicion, con latitud y longitud actuales
                                    posActual = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                                    Ext.getCmp("mapaCercaniaEventos").setMapCenter({latitude: posActual.lat(), longitude: posActual.lng()});
                                }
                                );
                            }
                        },
                        height: '80%',
                        id: 'botonVolverPosActualMapaEventos',
                        left: '2%',
                        top: '10%',
                        ui: 'confirm-round',
                        width: '15%',
                        text: '<p style="font-size: 40%;"> Ir a pos </p> <p style="font-size: 40%;"> actual </p>'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onImagenLogoDidiMapaEventosTap',
                event: 'tap',
                delegate: '#imagenLogoDidiMapaEventos'
            }
        ]
    },

    onImagenLogoDidiMapaEventosTap: function(img, e, options) {
        //Todo logo de Didi redirige hacia el containerInicio
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));
        //Al salir del mapa, hay que hacer visible el tabBar nuevamente
        Ext.getCmp("tabPanelPrincipal").getTabBar().setHidden(0);
    }

});