/*
 * File: app/view/containerFavoritosEmpresasPerfilUsuario.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerFavoritosEmpresasPerfilUsuario', {
    extend: 'Ext.Container',
    alias: 'widget.containerfavoritosempresasperfilusuario',

    config: {
        id: 'containerFavoritosEmpresasPerfilUsuario',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: '10%',
                id: 'toolbarContainerFavoritosEmpresasPerfilUsuario',
                style: 'background: #3E3737',
                items: [
                    {
                        xtype: 'image',
                        centered: true,
                        height: '100%%',
                        html: '<img src="./resources/logo/Logo_DD.png" width="100%" height="100%">',
                        id: 'imagenToolbarContainerFavoritosEmpresasPerfilUsuario',
                        itemId: 'myimage30',
                        width: '40%'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //Esta linea es para cambiar al tab anterior
                            //Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));



                            Ext.getCmp('containerDelPerfilUsuario').setHidden(0);


                            var main = Ext.get('containerParaTabPanelPrincipal');


                            if (main.hasCls('out')) {
                                main.removeCls('out');
                                main.addCls('in'); 
                                //button.setText('Usuario');
                            } else {
                                main.removeCls('in');    
                                main.addCls('out');    
                                //button.setText('Usuario');         
                            }


                        },
                        baseCls: 'botonUsuario',
                        height: '60%',
                        id: 'botonAtrasContainerFavoritosEmpresasPerfilUsuario',
                        left: '1%',
                        top: '20%',
                        ui: 'action-round',
                        width: '13%'
                    }
                ]
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'titleBarFavoritosEmpresasPerfilUsuario',
                title: 'Empresas'
            },
            {
                xtype: 'list',
                id: 'listaFavoritosEmpresasSPerfilUsuario',
                itemId: 'mylist7',
                emptyText: 'No tiene empresas favoritas.',
                itemTpl: [
                    '<div>',
                    '    <table border="0" height="100" style=\'table-layout:fixed; width: 100%;\'>',
                    '',
                    '    <col width="25%">',
                    '    <col width="50%">',
                    '    <col width="25%">',
                    '    <tr>',
                    '        <td>',
                    '            <p> <img src={banner} height="80" width="80%" /> </p>',
                    '        </td>',
                    '        <td  class="customfont">',
                    '            <p><font size="4"><font face="sansation"><p> {nombre} </p></font></font></p>',
                    '            <p><font size="2"><font face="verdana"><p> {telefono} </p></font></font></p>',
                    '            <p><font size="2"><p> {provincia} </p></font></p>',
                    '        </td>',
                    '        <td align="right">',
                    '            <input type="button" id="botonVerDescEmpresaFavoritaPerfilUsuario" class="botonDescripcion" name="" style="padding:3px; color:green; height:35px; width: 85%;">',
                    '            <input type="button" id="botonBorrarEmpresaFavoritaPerfilUsuario" class="botonBorrar" name="" style="padding:3px; color:green; height:35px; width: 85%;">',
                    '        </td>',
                    '        </tr>',
                    '</table>',
                    '</div>',
                    ''
                ],
                loadingText: 'Cargando...',
                store: 'storeExtraccionFavoritasEmpresasPerfilUsuario',
                grouped: true,
                indexBar: {
                    id: 'indexBarEmpresasFavoritasPerfilUsuario'
                },
                plugins: [
                    {
                        autoPaging: true,
                        loadMoreText: 'Cargar más...',
                        noMoreRecordsText: 'Final',
                        type: 'listpaging'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onImagenToolbarContainerSubcategoriasTap1',
                event: 'tap',
                delegate: '#imagenToolbarContainerFavoritosEmpresasPerfilUsuario'
            },
            {
                fn: 'onListaFavoritosEmpresasSPerfilUsuarioItemSwipe',
                event: 'itemswipe',
                delegate: '#listaFavoritosEmpresasSPerfilUsuario'
            }
        ]
    },

    onImagenToolbarContainerSubcategoriasTap1: function(img, e, options) {
        //Para devolverse hacia container Inicio dando click en el Logo Didi
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));
    },

    onListaFavoritosEmpresasSPerfilUsuarioItemSwipe: function(dataview, index, target, record, e, options) {
        funcionEliminadoEmpresasFavoritasPerfilUsuario=function(buttonId){
            if(buttonId=="no"){
                //
            }
            else{


                //Se refrescan los parametros para paging del store
                Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").loadPage(1);

                Ext.getStore("storeEnvioAgregadoFavoritosEmpresasPerfilUsuario").getProxy().setUrl("http://www.didicr.com/php/didiFavorito/borraEmpresaFavoritaPorIdUsuarioEmpresaFavorita.php");
                Ext.getStore("storeEnvioAgregadoFavoritosEmpresasPerfilUsuario").getProxy().setExtraParam('idUsuarioEmpresaFavoritaParam',record.get("idUsuarioEmpresaFavorita"));
                //alert(record.get("idUsuarioEmpresaFavorita"));
                Ext.getStore("storeEnvioAgregadoFavoritosEmpresasPerfilUsuario").load();
                //alert("fdet");
                //        Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").getProxy().setExtraParam('idUsuarioParam',3);
                Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").load();
                Ext.Msg.alert('Aviso', 'Empresa eliminada exitosamente.', Ext.emptyFn);
            }
            //
        };





        extMessageBox=Ext.Msg.confirm("Aviso", "Desea eliminar esta empresa de sus favoritas?", funcionEliminadoEmpresasFavoritasPerfilUsuario);





        //Ext.Msg.confirm("Aviso", "Desea eliminar esta empresa de sus favoritas?", funcionEliminadoEmpresasFavoritasPerfilUsuario);






    }

});