/*
 * File: app/view/containerAppDidiRapidos.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerAppDidiRapidos', {
    extend: 'Ext.Container',
    alias: 'widget.containerappdidirapidos',

    config: {
        html: '<b>App del DiDiRapido marcado..</b>',
        id: 'containerAppDidiRapidos',
        itemId: 'containerAppDidiRapidos',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: '10%',
                id: 'toolbarContainerAppDidiRapido',
                style: 'background: #3E3737',
                items: [
                    {
                        xtype: 'image',
                        centered: true,
                        height: '100%%',
                        html: '<img src="./resources/logo/Logo_DD.png" width="100%" height="100%">',
                        id: 'imagenToolbarContainerAppDidiRapido',
                        itemId: 'myimage1',
                        width: '40%'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //Esta linea es para cambiar al tab Inicio
                            Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));
                        },
                        baseCls: 'botonAtras',
                        height: '80%',
                        id: 'botonAtrasContainerAppDidiRapidos',
                        right: '2%',
                        top: '10%',
                        ui: 'action-round',
                        width: '15%'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onImagenToolbarContainerAppDidiRapidoTap',
                event: 'tap',
                delegate: '#imagenToolbarContainerAppDidiRapido'
            }
        ]
    },

    onImagenToolbarContainerAppDidiRapidoTap: function(img, e, options) {
        //Todas las imagenes de DiDiLogo escucharan un evento para regresar al container
        //inicio al ser presionadas
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));
    }

});