/*
 * File: app/view/containerMapa.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerMapa', {
    extend: 'Ext.Container',
    alias: 'widget.containermapa',

    config: {
        html: '<img src="./resources/css/esp/botones/mapa/DD_fondo_mapa.png" height="100%" width="100%"/>',
        id: 'containerMapa',
        cls: [
            'fondoMapa'
        ],
        items: [
            {
                xtype: 'panel',
                height: '45%',
                id: 'panelEscogenciaEntreMapaEventosOMapaEmpresas',
                left: '25%',
                top: '30%',
                width: '50%',
                layout: {
                    type: 'fit'
                },
                modal: true,
                items: [
                    {
                        xtype: 'button',
                        baseCls: 'botonMapaDe',
                        docked: 'top',
                        height: '25%',
                        width: '100%'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //Se oculta el tabBar del mapa Eventos
                            Ext.getCmp("tabPanelPrincipal").getTabBar().setHidden(1);
                            //Se especifica el view del que se pasa a dicho mapa, asi como se hace el 
                            //cargado del store necesario para el dataView con las categorias de eventos
                            viewDelQuePasoHaciaMapaEventos="containerInicio";
                            Ext.getStore("storeCategoriasEventos").load();
                            //Se hace visible el dataView con las categorias de eventos
                            Ext.getCmp("dataViewDidiMapaEventos").setHidden(0);
                            //Se borran los marker en el mapa si es que los tenia
                            while(markersMapaEventos[0]){
                                markersMapaEventos.pop().setMap(null);
                            }
                            //Se pasa al view de ese mapa de Eventos
                            Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerMapaEventos"));
                            //Se setea el zoom del mapa, por si el usuario lo ha modificado
                            Ext.getCmp("mapaCercaniaEventos").setMapOptions({zoom: 13});
                        },
                        baseCls: 'botonMapaEvento',
                        docked: 'top',
                        height: '35.5%',
                        id: 'botonEleccionMapaPorEventos',
                        ui: 'confirm-round',
                        width: '100%'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //Se he elegido el view de mapa por Empresas, entonces se pasa a ese
                            Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerMapaPrincipal"));
                            //Se borran los pines de ese mapa si es que los tenia
                            while(markersMapaPrincipal[0]){
                                markersMapaPrincipal.pop().setMap(null);
                            }
                        },
                        baseCls: 'botonMapaEmpresas',
                        docked: 'top',
                        height: '35.5%',
                        id: 'botonEleccionMapaPorEmpresas',
                        ui: 'confirm-round',
                        width: '100%'
                    }
                ]
            }
        ]
    }

});