/*
 * File: app/view/containerFormularioGeolocalizacion.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerFormularioGeolocalizacion', {
    extend: 'Ext.Container',
    alias: 'widget.containerformulariogeolocalizacion',

    config: {
        id: 'containerFormularioGeolocalizacion',
        itemId: 'containerFormularioGeolocalizacion',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: '10%',
                id: 'toolbarContainerGeolocalizacion',
                style: 'background: #3E3737',
                items: [
                    {
                        xtype: 'image',
                        centered: true,
                        height: '100%%',
                        html: '<img src="./resources/logo/Logo_DD.png" width="100%" height="100%">',
                        id: 'imagenToolbarContainerGeolocalizacion',
                        itemId: 'myimage18',
                        width: '40%'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //Se devuleve hacia containerInicio, ya que se esta en busqueda
                            Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));
                        },
                        baseCls: 'botonAtras',
                        height: '80%',
                        id: 'botonAtrasContainerGeolocalizacion',
                        right: '2%',
                        top: '10%',
                        ui: 'action-round',
                        width: '15%'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                height: '25%',
                id: 'fieldSetBusquedaPorGeolocalizacion',
                style: 'background-color: white',
                top: '15%',
                width: '100%',
                items: [
                    {
                        xtype: 'textfield',
                        height: '50%',
                        id: 'textFieldBusquedaPorGeolocalizacion1',
                        width: '100%',
                        label: '<center> Búsqueda </center>',
                        labelWidth: '100%'
                    },
                    {
                        xtype: 'textfield',
                        height: '50%',
                        id: 'textFieldBusquedaPorGeolocalizacion2',
                        width: '100%',
                        placeHolder: 'Digite aquí su búsqueda'
                    }
                ]
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    //Se quiere hacer una busqueda por geolocalizacion... pero se quiere utilizar la
                    //misma lista de listadoTotal Empresas... pero para esto, hay que comenzar por
                    //cambiar el Url del proxy que le corresponde al store que le corresponde:
                    Ext.getStore("storeListaEmpresasEnSubcategoria").getProxy().setUrl("http://www.didicr.com/php/busqueda/geolocalizacion/busquedaGeolocalizacionListado.php");


                    if (navigator.geolocation) {
                        navigator.geolocation.getCurrentPosition(
                        function(position){
                            //Se crea un objeto de posicion, con latitud y longitud actuales
                            posActual = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                            //Ext.getCmp("mapaContainerMapa").setMapCenter({latitude: posActual.lat(), longitude: posActual.lng()});
                        }
                        );
                    }


                    //alert(posActual.lat());
                    //alert(posActual.lng());

                    latMinimaFormulatioGeolocalizacion=posActual.lat()-(Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue())/100;
                    latMaximaFormulatioGeolocalizacion=posActual.lat()+(Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue())/100;
                    lngMinimaFormulatioGeolocalizacion=posActual.lng()-(Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue())/100;
                    lngMaximaFormulatioGeolocalizacion=posActual.lng()+(Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue())/100;


                    Ext.getStore("storeListaEmpresasEnSubcategoria").loadPage(1);


                    Ext.getStore("storeListaEmpresasEnSubcategoria").getProxy().setExtraParam('latitudMinimaParam',latMinimaFormulatioGeolocalizacion);
                    Ext.getStore("storeListaEmpresasEnSubcategoria").getProxy().setExtraParam('latitudMaximaParam',latMaximaFormulatioGeolocalizacion);
                    Ext.getStore("storeListaEmpresasEnSubcategoria").getProxy().setExtraParam('longitudMinimaParam',lngMinimaFormulatioGeolocalizacion);
                    Ext.getStore("storeListaEmpresasEnSubcategoria").getProxy().setExtraParam('longitudMaximaParam',lngMaximaFormulatioGeolocalizacion);



                    //Luego, hay que pasar por extraparam la palabra que se escribio en el campo
                    //proporcionado al usuario
                    Ext.getStore("storeListaEmpresasEnSubcategoria").getProxy().setExtraParam('palabraBusquedaListadoParam',Ext.getCmp("textFieldBusquedaPorGeolocalizacion2").getValue());
                    viewDelQuePasoHaciaListadoTotalEmpresas="containerFormularioGeolocalizacion";
                    Ext.getStore("storeListaEmpresasEnSubcategoria").load();
                },
                height: '20%',
                id: 'botonBusquedaPorGeolocalizacionListadoEmpresas',
                left: '10%',
                top: '75%',
                width: '32%',
                text: 'Listado'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    //Se pasa hacia el container de mapa, luego se borran los markers ahi, despues
                    //se oculta el dataView con las categorias de Empresas, 
                    Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerMapaPrincipal"));
                    while(markersMapaPrincipal[0]){
                        markersMapaPrincipal.pop().setMap(null);
                    }
                    Ext.getCmp("dataViewDidiMapaPrincipalEnTabPanel").setHidden(1);
                    //Se quiere hacer una busqueda por geolocalizacion... pero se quiere utilizar la
                    //misma lista de listadoTotal Empresas... pero para esto, hay que comenzar por
                    //cambiar el Url del proxy que le corresponde al store que le corresponde:
                    Ext.getStore("storeListadoTotalDeLasEmpresas").getProxy().setUrl("http://www.didicr.com/php/busqueda/geolocalizacion/busquedaGeolocalizacionMapa.php");
                    //Luego, hay que pasar por extraparam la palabra que se escribio en el campo
                    //proporcionado al usuario

                    if (navigator.geolocation) {
                        navigator.geolocation.getCurrentPosition(
                        function(position){
                            //Se crea un objeto de posicion, con latitud y longitud actuales
                            posActual = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                            //Ext.getCmp("mapaContainerMapa").setMapCenter({latitude: posActual.lat(), longitude: posActual.lng()});
                        }
                        );
                    }


                    //alert(posActual.lat());
                    //alert(posActual.lng());

                    latMinimaFormulatioGeolocalizacion=posActual.lat()-(Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue())/100;
                    latMaximaFormulatioGeolocalizacion=posActual.lat()+(Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue())/100;
                    lngMinimaFormulatioGeolocalizacion=posActual.lng()-(Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue())/100;
                    lngMaximaFormulatioGeolocalizacion=posActual.lng()+(Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue())/100;


                    //Ext.getStore("storeListadoTotalDeLasEmpresas").loadPage(1);


                    Ext.getStore("storeListadoTotalDeLasEmpresas").getProxy().setExtraParam('latitudMinimaParam',latMinimaFormulatioGeolocalizacion);
                    Ext.getStore("storeListadoTotalDeLasEmpresas").getProxy().setExtraParam('latitudMaximaParam',latMaximaFormulatioGeolocalizacion);
                    Ext.getStore("storeListadoTotalDeLasEmpresas").getProxy().setExtraParam('longitudMinimaParam',lngMinimaFormulatioGeolocalizacion);
                    Ext.getStore("storeListadoTotalDeLasEmpresas").getProxy().setExtraParam('longitudMaximaParam',lngMaximaFormulatioGeolocalizacion);


                    Ext.getStore("storeListadoTotalDeLasEmpresas").getProxy().setExtraParam('palabraBusquedaListadoParam',Ext.getCmp("textFieldBusquedaPorGeolocalizacion2").getValue());
                    funcionParaIntroducirMarkersEnMapa("storeListadoTotalDeLasEmpresas",Ext.getCmp("mapaContainerMapa"));
                    //Se ajusta el mapOptions por si el usuario lo modifico
                    //Ext.getCmp("mapaContainerMapa").setMapOptions({zoom: 14});
                },
                height: '20%',
                id: 'botonBusquedaPorGeolocalizacionMapa',
                right: '10%',
                top: '75%',
                width: '32%',
                text: 'Mapa'
            },
            {
                xtype: 'container',
                height: '5%',
                html: '<b><center> Ver resultados por: </center></b>',
                id: 'containerTituloBotonesBusquedaGeolocalizacion',
                top: '65%',
                width: '100%'
            },
            {
                xtype: 'container',
                height: '10%',
                html: '<b><center> Búsqueda por lugar </center></b>',
                id: 'containerTituloBusquedaPorGeolocalizacion',
                top: '2%',
                width: '100%'
            },
            {
                xtype: 'sliderfield',
                id: 'sliderFieldKmFormularioGeoilocalizacion',
                itemId: 'mysliderfield',
                top: '42%',
                width: '100%',
                value: [
                    0
                ],
                increment: 0.1,
                maxValue: 25
            },
            {
                xtype: 'container',
                height: '7%',
                html: '<center> <p> 0 km </p> </center>',
                id: 'containerKmFormularioGeolocalizacion',
                left: '40%',
                top: '56%',
                width: '20%'
            }
        ],
        listeners: [
            {
                fn: 'onImagenToolbarContainerGeolocalizacionTap',
                event: 'tap',
                delegate: '#imagenToolbarContainerGeolocalizacion'
            },
            {
                fn: 'onSliderFieldKmFormularioGeoilocalizacionChange',
                event: 'change',
                delegate: '#sliderFieldKmFormularioGeoilocalizacion'
            }
        ]
    },

    onImagenToolbarContainerGeolocalizacionTap: function(img, e, options) {
        //Todo logo de Didi redirige hacia containerInicio
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));
    },

    onSliderFieldKmFormularioGeoilocalizacionChange: function(slider, Slider, thumb, newValue, oldValue, options) {
        //alert();
        //alert("<center> <p> "+Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue().slice(0,5)+" km </p> </center>");
        stringParaKmFormularioGeolocalizacion=" "+Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue();

        Ext.getCmp("containerKmFormularioGeolocalizacion").setHtml("<center> <p>"+stringParaKmFormularioGeolocalizacion.slice(0,5)+" km </p> </center>");

        //

        //alert(Ext.getCmp("sliderFieldKmFormularioGeoilocalizacion").getValue());


    }

});