/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    viewport: {
        id: 'viewportAspogamo'
    },

    models: [
        'modelPrueba'
    ],
    stores: [
        'storePrueba'
    ],
    views: [
        'tabPanelPrincipal',
        'containerHome',
        'containerMain',
        'containerHeader',
        'containerProfile',
        'containerMyVideos',
        'containerPopular',
        'BASURERO'
    ],
    name: 'MyApp',

    launch: function() {

        variableParaDetenerDibujado=0;

        funcionDibujadoEnCanvas=function(){
            //alert("gwerhg");
            if(variableParaDetenerDibujado===1){
                //alert("gwerg;j");
                //
                for(var i=0; i<arregloDePuntosDibujoX.length; i++){
                    //
                    canvasContext=variableContainerVideoPopularCanvas.getContext("2d");
                    canvasContext.strokeStyle='rgb(55,55,255)';
                    canvasContext.beginPath();
                    if(arregloDePuntosDibujoBool[i]!==1){
                        canvasContext.moveTo(arregloDePuntosDibujoX[i-1],arregloDePuntosDibujoY[i-1]);
                    }
                    canvasContext.lineTo(arregloDePuntosDibujoX[i],arregloDePuntosDibujoY[i]);
                    canvasContext.stroke();
                    canvasContext.closePath();
                }
            }
            setTimeout(funcionDibujadoEnCanvas, 10);
        };


        setTimeout(funcionDibujadoEnCanvas,2000);

        Ext.create('MyApp.view.containerMain', {fullscreen: true});
    }

});
