/*
 * File: app/controller/controladorListaFavoritosEventosPerfilUsuario.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.controladorListaFavoritosEventosPerfilUsuario', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            list: '#listaFavoritosEventosPerfilUsuario'
        },

        control: {
            "list": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        if(e.target.id=="botonBorrarEventoFavoritoPerfilUsuario"){
            //Esta funcion, y el Msg 

            funcionEliminadoEventosFavoritosPerfilUsuario=function(buttonId){
                if(buttonId=="no"){
                    //
                }
                else{
                    Ext.getStore("storeEnvioAgregadoFavoritosPerfilUsuario").getProxy().setUrl("http://www.didicr.com/php/didiFavorito/borraEventoFavoritoPorIdEventoFavorito.php");
                    Ext.getStore("storeEnvioAgregadoFavoritosPerfilUsuario").getProxy().setExtraParam('idUsuarioEventoFavoritoParam',record.get("idUsuarioEventoFavorito"));
                    //alert(record.get("idUsuarioEventoFavorito"));
                    Ext.getStore("storeEnvioAgregadoFavoritosPerfilUsuario").load();
                    //alert("fdet");
                    //        Ext.getStore("storeExtraccionFavoritosPerfilUsuario").getProxy().setExtraParam('idUsuarioParam',3);
                    Ext.getStore("storeExtraccionFavoritosPerfilUsuario").load();
                    Ext.Msg.alert('Aviso', 'Evento eliminado exitosamente.', Ext.emptyFn);
                }
                //
            };

            extMessageBox=Ext.Msg.confirm("Aviso", "Desea eliminar este evento de sus favoritos?", funcionEliminadoEventosFavoritosPerfilUsuario);
        }
        if(e.target.id=="botonVerDescEventoFavoritoPerfilUsuario"){
            //Con este codigo se llama, al darle click en uno de los Cat Eventos, a la funcion
            //que abre la descripcion de eventos
            Ext.getCmp("containerFavoritosEventosPerfilUsuario").setMasked({xtype: 'loadmask', message: 'Espere por favor...'});
            funcionParaAbrirDescripcionEventos(record.get("idEvento"),"containerFavoritosEventosPerfilUsuario");
        }

        else{
            //Con este codigo se llama, al darle click en uno de los Cat Eventos, a la funcion
            //que abre la descripcion de eventos
            Ext.getCmp("containerFavoritosEventosPerfilUsuario").setMasked({xtype: 'loadmask', message: 'Espere por favor...'});
            funcionParaAbrirDescripcionEventos(record.get("idEvento"),"containerFavoritosEventosPerfilUsuario");
        }


    }

});