/*
 * File: app/controller/controladorDataViewCategorias.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.controladorDataViewCategorias', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            dataview: '#dataViewCategorias'
        },

        control: {
            "dataview": {
                itemtap: 'onDataviewItemTap'
            }
        }
    },

    onDataviewItemTap: function(dataview, index, target, record, e, options) {
        Ext.getCmp("containerCategorias").setMasked({xtype: 'loadmask', message: 'Espere por favor...'});



        //Se resetea el parametro start para el listPaging plugin
        Ext.getStore("storeSubcategorias").loadPage(1);


        //Con estas lineas, al pasar a Subcategorias, se pasa un parametro a el store que
        //corresponde con el listado de subcategorias, y ademas se carga el store
        Ext.getStore("storeSubcategorias").getProxy().setExtraParam('catParam',record.get("idCategoria"));
        viewDelQuePasoHaciaSubcategorias="containerCategorias";
        Ext.getStore("storeSubcategorias").load();
        //Cuando se da click en categorias, y se pasa al listado de las subcategorias,
        //se tiene una imagen, un banner para la empresa principal de esta categoria
        Ext.getCmp("imagenBannerEmpresaPrincipalCategoria").setHtml("<img src="+record.get("bannerUrl")+" height='100%' width='100%'/>");


        /*
        //Dependiendo de en donde este uno, si esta en Busqueda Avanzada, entonces al
        //cargar el store Subcategorias lo unico que se hace es ocultar el panel de
        //Categorias (ya que se le ha dado click a alguna de las categorias), y en caso
        //contrario lo q se hace es abrir el container de Subcategorias
        if(Ext.getCmp("panelCategoriaBusquedaAvanzada").getHidden()===true){
            Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerSubcategorias"));
        }
        else{
            Ext.getCmp("panelCategoriaBusquedaAvanzada").setHidden(1);
        }
        */






    }

});