/*
 * File: app/controller/controladorListaFavoritosEmpresasPerfilUsuario.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.controladorListaFavoritosEmpresasPerfilUsuario', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            list: '#listaFavoritosEmpresasSPerfilUsuario'
        },

        control: {
            "list": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        if(e.target.id=="botonBorrarEmpresaFavoritaPerfilUsuario"){
            funcionEliminadoEmpresasFavoritasPerfilUsuario=function(buttonId){
                if(buttonId=="no"){
                    //
                }
                else{



                    //Se refrescan los parametros para paging del store
                    Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").loadPage(1);

                    Ext.getStore("storeEnvioAgregadoFavoritosEmpresasPerfilUsuario").getProxy().setUrl("http://www.didicr.com/php/didiFavorito/borraEmpresaFavoritaPorIdUsuarioEmpresaFavorita.php");
                    Ext.getStore("storeEnvioAgregadoFavoritosEmpresasPerfilUsuario").getProxy().setExtraParam('idUsuarioEmpresaFavoritaParam',record.get("idUsuarioEmpresaFavorita"));
                    //alert(record.get("idUsuarioEmpresaFavorita"));
                    Ext.getStore("storeEnvioAgregadoFavoritosEmpresasPerfilUsuario").load();
                    //alert("fdet");
                    //        Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").getProxy().setExtraParam('idUsuarioParam',3);
                    Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").load();
                    Ext.Msg.alert('Aviso', 'Empresa eliminada exitosamente.', Ext.emptyFn);
                }
                //
            };




            extMessageBox=Ext.Msg.confirm("Aviso", "Desea eliminar esta empresa de sus favoritas?", funcionEliminadoEmpresasFavoritasPerfilUsuario);
        }
        if(e.target.id=="botonVerDescEmpresaFavoritaPerfilUsuario"){

            Ext.getCmp("containerFavoritosEmpresasPerfilUsuario").setMasked({xtype: 'loadmask', message: 'Espere por favor...'});
            //alert(record.get("tipoPlan"));
            if(record.get("tipoPlan")<4){
                botonClickeadoEnListadoTotalEmpresas="";
                funcionParaAbrirDescEmpresa(record.get("idCliente"),"containerFavoritosEmpresasPerfilUsuario");
            }

        }
        else{

            Ext.getCmp("containerFavoritosEmpresasPerfilUsuario").setMasked({xtype: 'loadmask', message: 'Espere por favor...'});
            //alert(record.get("tipoPlan"));
            if(record.get("tipoPlan")<4){
                botonClickeadoEnListadoTotalEmpresas="";
                funcionParaAbrirDescEmpresa(record.get("idCliente"),"containerFavoritosEmpresasPerfilUsuario");
            }

        }


    }

});