/*
 * File: app/controller/controladorDataviewCategoriasBusquedaAvanzada.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.controladorDataviewCategoriasBusquedaAvanzada', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            dataview: '#dataCategoriaBusquedaAvanzada'
        },

        control: {
            "dataview": {
                itemtap: 'onDataviewItemTap'
            }
        }
    },

    onDataviewItemTap: function(dataview, index, target, record, e, options) {
        //Con estas dos lineas se filtran las subcategorias, y se carga el store de
        //subcategorias, para la lista en busqueda avanzada
        Ext.getStore("storeSubcategorias").getProxy().setExtraParam('cat',record.get("nombre"));
        Ext.getStore("storeSubcategorias").load();
        //Con esta linea se asigna al boton de Categorias en busq avanzada, el texto
        //el nombre de la categoria a la que se le dio click
        Ext.getCmp("botonCategoriaBusquedaAvanzada").setText("<p style='font-size: 60%;'> " +record.get("nombre")+ "</p>");
        Ext.getCmp("botonCategoriaBusquedaAvanzada").setItemId(record.get("nombre"));
    }

});