/*
 * File: app/controller/controladorListaCatEventos.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.controladorListaCatEventos', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            list: '#listaSubEventos'
        },

        control: {
            "list": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        Ext.getCmp("containerSubEventos").setMasked({xtype: 'loadmask', message: 'Espere por favor...'});

        //Con este codigo se llama, al darle click en uno de los Cat Eventos, a la funcion
        //que abre la descripcion de eventos
        funcionParaAbrirDescripcionEventos(record.get("idEvento"),"containerSubEventos");
    }

});