/*
 * File: app/store/storeDidiRapidos.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeDidiRapidos', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelDidiRapidos'
    ],

    config: {
        autoSync: true,
        model: 'MyApp.model.modelDidiRapidos',
        storeId: 'storeDidiRapidos',
        proxy: {
            type: 'jsonp',
            url: 'http://www.didicr.com/php/didiRapidos.php',
            reader: {
                type: 'json',
                idProperty: 'idDIdiRapidos',
                rootProperty: 'ptm'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        //Con estas dos lineas se activa el Container de Inicio, y se hace que
        //vuelva a aparecer el Tab Bar
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerInicio"));
        Ext.getCmp("tabPanelPrincipal").getTabBar().setHidden(0);

        Ext.getCmp("dataViewDidiRapidos").setStore(Ext.getStore("storeDidiRapidos"));
    }

});