/*
 * File: app/store/storeSubcategorias.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeSubcategorias', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelSubcategorias'
    ],

    config: {
        autoSync: true,
        clearOnPageLoad: false,
        model: 'MyApp.model.modelSubcategorias',
        pageSize: 15,
        storeId: 'storeSubcategorias',
        totalCount: 20,
        proxy: {
            type: 'jsonp',
            url: 'http://www.didicr.com/php/subcategoria/subcategoriaPorCategoria.php',
            reader: {
                type: 'json',
                idProperty: 'idSubcategoria',
                rootProperty: 'ptm'
            }
        },
        grouper: {
            groupFn: function(record) {
                return record.get("nombre")[0];
            }
        },
        sorters: {
            property: 'subcategoria'
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        //Con este codigo se filtran las letras en el indexBar
        contadorSeteadoDeLetrasIndexBarSubcategorias=0;
        var letrasParaSetearIndexBar = [];
        Ext.getStore("storeSubcategorias").each(function (record) {
            if(letrasParaSetearIndexBar.indexOf(record.get("nombre")[0])==-1){
                letrasParaSetearIndexBar[contadorSeteadoDeLetrasIndexBarSubcategorias]=record.get("nombre")[0];
                contadorSeteadoDeLetrasIndexBarSubcategorias++;
            }
        });
        //Luego de crear el array, se asigna al indexBar ese array
        Ext.getCmp("indexBarSubcategorias").setLetters(letrasParaSetearIndexBar);


        //Dependiendo de en donde este uno, si esta en Busqueda Avanzada, entonces al
        //cargar el store Subcategorias lo unico que se hace es ocultar el panel de
        //Categorias (ya que se le ha dado click a alguna de las categorias), y en caso
        //contrario lo q se hace es abrir el container de Subcategorias
        if(Ext.getCmp("panelCategoriaBusquedaAvanzada").getHidden()===true){
            Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerSubcategorias"));
        }
        else{
            Ext.getCmp("panelCategoriaBusquedaAvanzada").setHidden(1);
        }



    }

});