/*
 * File: app/store/storeReservaEvento.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeReservaEvento', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelReservaEvento'
    ],

    config: {
        autoSync: true,
        clearOnPageLoad: false,
        model: 'MyApp.model.modelReservaEvento',
        pageSize: 5,
        storeId: 'storeReservaEvento',
        proxy: {
            type: 'jsonp',
            extraParams: {
                idUsuarioPara: '3'
            },
            url: 'http://www.didicr.com/php/didiReserva/reservaPorUsuario4.php',
            reader: {
                type: 'json',
                rootProperty: 'ptm'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        Ext.getCmp("containerReservasPerfilUsuario").setMasked(false);
    }

});