/*
 * File: app/store/storeExtraccionFavoritasEmpresasPerfilUsuario.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeExtraccionFavoritasEmpresasPerfilUsuario', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelListaEmpresasEnSubcategoria'
    ],

    config: {
        autoSync: true,
        clearOnPageLoad: false,
        model: 'MyApp.model.modelListaEmpresasEnSubcategoria',
        pageSize: 5,
        storeId: 'storeExtraccionFavoritasEmpresasPerfilUsuario',
        proxy: {
            type: 'jsonp',
            url: 'http://www.didicr.com/php/didiFavorito/empresaFavoritaPorUsuario2.php',
            reader: {
                type: 'json',
                rootProperty: 'ptm'
            }
        },
        grouper: {
            groupFn: function(record) {
                return record.get("nombre")[0];
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        //indexBarEmpresasFavoritasPerfilUsuario


        //Con este codigo se filtran las letras en el indexBar
        contadorSeteadoDeLetrasIndexBarEmpresasFavoritas=0;
        var letrasParaSetearIndexBarEmpresasFavoritas = [];
        Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").each(function (record) {
            if(letrasParaSetearIndexBarEmpresasFavoritas.indexOf(record.get("nombre")[0])==-1){
                letrasParaSetearIndexBarEmpresasFavoritas[contadorSeteadoDeLetrasIndexBarEmpresasFavoritas]=record.get("nombre")[0];
                contadorSeteadoDeLetrasIndexBarEmpresasFavoritas++;
            }
        });
        //Luego de crear el array, se asigna al indexBar ese array
        Ext.getCmp("indexBarEmpresasFavoritasPerfilUsuario").setLetters(letrasParaSetearIndexBarEmpresasFavoritas);


        //alert(Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").getProxy().getStartParam());
        //alert(Ext.getStore("storeExtraccionFavoritasEmpresasPerfilUsuario").getProxy().getLimittParam());
        //alert("fawe4;f");

        /*
        alert(this.getCount());
        alert(this.getProxy().getStartParam());
        */

        //alert(this.);


        Ext.getCmp("containerFavoritosEmpresasPerfilUsuario").setMasked(false);

    }

});