/*
 * File: app/store/storeCategoriasEventos.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeCategoriasEventos', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelCategoriasEventos'
    ],

    config: {
        autoSync: true,
        model: 'MyApp.model.modelCategoriasEventos',
        storeId: 'storeCategoriasEventos',
        proxy: {
            type: 'jsonp',
            url: 'http://www.didicr.com/php/eventoCategorias.php',
            reader: {
                type: 'json',
                idProperty: 'idEventoCategorias',
                rootProperty: 'ptm'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        //Finalmente, se pasa a ese view que contiene al mapa de Eventos
        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerMapaEventos"));
    }

});