/*
 * File: app/store/storeModuloProducto.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeModuloProducto', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelModuloProducto'
    ],

    config: {
        autoSync: true,
        clearOnPageLoad: false,
        model: 'MyApp.model.modelModuloProducto',
        storeId: 'storeModuloProducto',
        proxy: {
            type: 'jsonp',
            url: 'http://www.didicr.com/php/producto/productoPorCliente.php',
            reader: {
                type: 'json',
                rootProperty: 'ptm'
            }
        },
        grouper: {
            groupFn: function(record) {
                return record.get("tipoProducto");
            }
        },
        sorters: {
            property: 'tipoProducto'
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        //Con este codigo se filtran las letras en el indexBar
        contadorSeteadoDeLetrasIndexBarModuloProducto=0;
        var letrasParaSetearIndexBar = [];
        Ext.getStore("storeModuloProducto").each(function (record) {
            if(letrasParaSetearIndexBar.indexOf(record.get("tipoProducto")[0])==-1){
                letrasParaSetearIndexBar[contadorSeteadoDeLetrasIndexBarModuloProducto]=record.get("tipoProducto")[0];
                contadorSeteadoDeLetrasIndexBarModuloProducto++;
            }
        });
        //Luego de crear el array, se asigna al indexBar ese array
        Ext.getCmp("indexBarModuloProducto").setLetters(letrasParaSetearIndexBar);










        Ext.getCmp("tabPanelPrincipal").add(containerModuloProductosDescEmpresa);

        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerProductosDescEmpresa"));

    }

});