/*
 * File: app/store/storeVerificadoEmpresaFavoritaPerfilUsuario.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeVerificadoEmpresaFavoritaPerfilUsuario', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelEnvioAgregadoFavoritosEmpresasPerfilUsuario'
    ],

    config: {
        model: 'MyApp.model.modelEnvioAgregadoFavoritosEmpresasPerfilUsuario',
        storeId: 'storeVerificadoEmpresaFavoritaPerfilUsuario',
        proxy: {
            type: 'jsonp',
            url: 'http://www.didicr.com/php/didiFavorito/verificaEmpresaFavoritaUsuario2.php',
            reader: {
                type: 'json',
                rootProperty: 'ptm'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        //alert("fef;g");
        try{
            //    alert(records[0].get("estado"));
            if(records[0].get("estado")==1){
                //        alert("f;alekf");
                Ext.getCmp("botonFavoritosContainerDescripcionEmpresa").disable();
            }
            else{
                Ext.getCmp("botonFavoritosContainerDescripcionEmpresa").enable();
            }
        }
        catch(e){
            Ext.getCmp("botonFavoritosContainerDescripcionEmpresa").enable();
        }
        //variableEjecutoCodigoEnStoreAgregadoEventosFavoritos=0;

    }

});