/*
 * File: app/store/storeModuloPromocion.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeModuloPromocion', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelModuloPromocion'
    ],

    config: {
        model: 'MyApp.model.modelModuloPromocion',
        storeId: 'storeModuloPromocion',
        proxy: {
            type: 'jsonp',
            url: 'http://www.didicr.com/php/promocion/promocionPorCliente.php',
            reader: {
                type: 'json',
                rootProperty: 'ptm'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        //Con la llamada de este metodo lo que se hace es recorrer sobre todos los
        //elementos del store, y para cada uno de ellos, se hace un APPEND de imagenes
        //al carousel, cada imagen tiene un url presente en el store
        contadorParaAsignarIDimgsCarouselPromocionEmpresa=0;
        this.each(function (record) {
            //alert("fwrg");
            Ext.getCmp("carouselPromocionEmpresa").add(Ext.create('Ext.Img', {html: "<p><img src="+ record.get("imagenPromocion") +" height='70%' width='100%'></p>"+"<p>&nbsp</p><center><p>"+record.get("nombrePromocion")+"</p></center>", id: "imagenCarouselPromocionEmpresa"+contadorParaAsignarIDimgsCarouselPromocionEmpresa}));
            //Ext.getCmp("imagenCarouselInicio"+contadorParaAsignarIDimgsCarouselPromocionEmpresa).addListener('tap',funcionDarClickElementosCarouselInicio);
            contadorParaAsignarIDimgsCarouselPromocionEmpresa=contadorParaAsignarIDimgsCarouselPromocionEmpresa+1;
        });



        Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp("containerPromocionEmpresa"));
    }

});