/*
 * File: app/store/storeCarouselInicio.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeCarouselInicio', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelCarouselInicio'
    ],

    config: {
        autoSync: true,
        model: 'MyApp.model.modelCarouselInicio',
        storeId: 'storeCarouselInicio',
        proxy: {
            type: 'jsonp',
            url: 'http://www.didicr.com/php/bannerPrincipal.php',
            reader: {
                type: 'json',
                idProperty: 'id',
                rootProperty: 'ptm'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        //Funcion que se ejecuta cuando se da click en elementos del Carousel
        funcionDarClickElementosCarouselInicio=function(img){

            Ext.getCmp("containerInicio").setMasked({xtype: 'loadmask', message: 'Espere por favor...'});

            //Para el caso en que la imagen clickeada corresponda a pag web
            if(records[img.getId()[20]].get("tipo")==1){
                funcionParaAbrirPaginaWeb(records[img.getId()[20]].get("link"),img.getId());
            }
            //Para el caso de que corresponda a descripcion de empresa
            if(records[img.getId()[20]].get("tipo")==2){
                //alert(records[img.getId()[20]].get("link"));
                funcionParaAbrirDescEmpresa(records[img.getId()[20]].get("link"),"containerInicio");
            }
            //Para este caso corresponde con descripcion de evento
            if(records[img.getId()[20]].get("tipo")==3){
                funcionParaAbrirDescripcionEventos(records[img.getId()[20]].get("link"),"containerInicio");
            }
            //Para este caso corresponde a abrir cierto container
            if(records[img.getId()[20]].get("tipo")==4){
                Ext.getCmp("tabPanelPrincipal").setActiveItem(Ext.getCmp(records[img.getId()[20]].get("link")));
            }
        };


        //Con la llamada de este metodo lo que se hace es recorrer sobre todos los
        //elementos del store, y para cada uno de ellos, se hace un APPEND de imagenes
        //al carousel, cada imagen tiene un url presente en el store
        contadorParaAsignarIDimgs=0;
        this.each(function (record) {
            Ext.getCmp("carouselBannerPrincipal").add(Ext.create('Ext.Img', {html: "<img src="+ record.get("imagen") +" height='100%' width='100%'>", id: "imagenCarouselInicio"+contadorParaAsignarIDimgs}));
            Ext.getCmp("imagenCarouselInicio"+contadorParaAsignarIDimgs).addListener('tap',funcionDarClickElementosCarouselInicio);
            contadorParaAsignarIDimgs=contadorParaAsignarIDimgs+1;
        });


        //Aqui se crea una funcion, y se hace un llamado a ella, es decir, a traves de 
        //recursividad se hace que los elementos en el carousel esten cambiando continuamente
        var funcionCambioEstadoCarouselInicio = function() {
            var task = Ext.create('Ext.util.DelayedTask', function() {
                console.log('hi');
                Ext.getCmp("carouselBannerPrincipal").next();
                if(Ext.getCmp("carouselBannerPrincipal").getActiveIndex()==Ext.getCmp("carouselBannerPrincipal").getItems().length-2){Ext.getCmp("carouselBannerPrincipal").setActiveItem(0);}
                funcionCambioEstadoCarousel.call(this);
            }, this);
            task.delay(5000);
        };
        funcionCambioEstadoCarouselInicio();




        Ext.getStore("storeDidiRapidos").load();
    }

});