/*
 * File: app/store/storeEnvioSolicitudReserva.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeEnvioSolicitudReserva', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelEnvioSolicitudReserva'
    ],

    config: {
        model: 'MyApp.model.modelEnvioSolicitudReserva',
        storeId: 'storeEnvioSolicitudReserva',
        proxy: {
            type: 'jsonp',
            url: 'http://www.didicr.com/php/insertaReserva2.php',
            reader: {
                type: 'json',
                rootProperty: 'ptm'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {

        funcionDespliegaOpcionesReservaEvento=function(){
            //    alert("fed");
            Ext.getCmp("panelResumenOpcionesReservaEvento").setHidden(0);
            if(viewDelQuePasoAlViewDeReserva=="containerDescripcionEventos"){
                try{
                    cantidadDePersonasReserva=Ext.getCmp("spinnerFieldModuloReservaciones").getValue();
                }
                catch(e){
                    cantidadDePersonasReserva=1;
                }

                try{
                    mesaReserva=Ext.getCmp("datePickerReservacionRestaurante").getValue()['MyPickerSlotPanelElegirMesa'];
                }
                catch(e){
                    mesaReserva=0;
                }

                try{
                    ocasionReserva=Ext.getCmp("pickerElegirOcasion").getValue()['MyPickerSlotElegirOcasion'];
                }
                catch(e){
                    ocasionReserva="Vacío";
                }

                try{
                    notaAdicionalReserva=Ext.getCmp("textAreaNotaAdicionalModuloReservaciones").getValue();
                }
                catch(e){
                    notaAdicionalReserva="Vacío";
                }




                Ext.getCmp("containerEnPanelResumenOpcionesReservaEvento").setHtml("<center><b> Confirmación de reserva </b></center>"+"<p> &nbsp </p>"+"<b><p style='font-size:125%;'>Número de reserva:"+Ext.getStore('storeEnvioSolicitudReserva').first().get("idReserva")+"</p></b>"+"<p> &nbsp </p>"+"<p style='font-family:texgyrechorus;color:black;'>Organizador del evento: "+Ext.getStore('storeEnvioSolicitudReserva').first().get("nombre")+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Nombre del evento:"+Ext.getStore('storeDescripcionEventos').first().get("nombre")+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Fecha: "+Ext.getCmp('dateFieldReservacionRestaurante').getValue()+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Hora: "+Ext.getCmp('selectFieldHoraReservaRestaurante').getPlaceHolder()+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Cantidad de personas: "+cantidadDePersonasReserva+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Nota adicional: "+notaAdicionalReserva+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Mesa: "+mesaReserva+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Ocasión: "+ocasionReserva+"</p>"+"<p> &nbsp </p>");
            }
            else{

                try{
                    cantidadDePersonasReserva=Ext.getCmp("spinnerFieldModuloReservaciones").getValue();
                }
                catch(e){
                    cantidadDePersonasReserva=1;
                }

                try{
                    mesaReserva=Ext.getCmp("datePickerReservacionRestaurante").getValue()['MyPickerSlotPanelElegirMesa'];
                }
                catch(e){
                    mesaReserva=0;
                }

                try{
                    ocasionReserva=Ext.getCmp("pickerElegirOcasion").getValue()['MyPickerSlotElegirOcasion'];
                }
                catch(e){
                    ocasionReserva="Vacío";
                }

                try{
                    notaAdicionalReserva=Ext.getCmp("textAreaNotaAdicionalModuloReservaciones").getValue();
                }
                catch(e){
                    notaAdicionalReserva="Vacío";
                }



                //        Ext.getCmp("containerEnPanelResumenOpcionesReservaEvento").setHtml("bla");
                Ext.getCmp("containerEnPanelResumenOpcionesReservaEvento").setHtml("<center><b> Confirmación de reserva </b></center>"+"<p> &nbsp </p>"+"<b><p style='font-size:125%;'>Número de reserva:"+Ext.getStore('storeEnvioSolicitudReserva').first().get("idReserva")+"</p></b>"+"<p> &nbsp </p>"+"<p style='font-family:texgyrechorus;color:black;'>Fecha: "+Ext.getCmp('dateFieldReservacionRestaurante').getValue()+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Hora: "+Ext.getCmp('selectFieldHoraReservaRestaurante').getPlaceHolder()+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Cantidad de personas: "+cantidadDePersonasReserva+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Nota adicional: "+notaAdicionalReserva+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Mesa: "+mesaReserva+"</p>"+"<p style='font-family:texgyrechorus;color:black;'>Ocasión: "+ocasionReserva+"</p>"+"<p> &nbsp </p>");
            }
            //alert(Ext.getStore('storeDescripcionEventos').get("nombre"));
            //alert(Ext.getCmp('dateFieldReservacionRestaurante').getValue());
            //alert(Ext.getCmp('selectFieldHoraReservaRestaurante').getPlaceHolder());
        };

        Ext.Msg.alert('Aviso', 'Su reservación ha sido pedida satisfactoriamente.', funcionDespliegaOpcionesReservaEvento);




    }

});