/*
 * File: app/store/storeEnvioSolicitudTaxi.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeEnvioSolicitudTaxi', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelEstadoEnvio'
    ],

    config: {
        model: 'MyApp.model.modelEstadoEnvio',
        storeId: 'storeEnvioSolicitudTaxi',
        proxy: {
            type: 'jsonp',
            url: 'http://www.didicr.com/php/diditaxi/recibeSolicitud.php',
            reader: {
                type: 'json',
                rootProperty: 'ptm'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {


        //AQUI VA, UNA VEZ QUE SE CARGUE ESTE STORE, ES DECIR, UNA VEZ QUE SE ASIGNE
        //UN TAXI A ESTE USUARIO, EL CODIGO PARA EL MAPA






        if(successful===true){
            //Se oculta el boton de cancelar pedido taxi, puesto que ya hay un taxi para la persona
            //y no puede cancelar el pedido, pero si puede cancelar el taxi en camino
            Ext.getCmp("containerBotonCancelarPedidoTaxi").setHidden(1);
            //Se le da la opcion de aceptar el taxi
            extMessageBox=Ext.Msg.confirm('Hay un taxi para usted.', 'Desea aceptarlo?', funcionLadoPasajeroTaxiAsociado);
        }


























        //alert(Ext.getStore("storeEnvioSolicitudTaxi").first().get("idPedido"));


    }

});