/*
 * File: app/view/containerRegistroUser.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerRegistroUser', {
    extend: 'Ext.Container',
    alias: 'widget.containerregistrouser',

    config: {
        id: 'containerRegistroUser',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Register',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp("tabPanelInicial").setActiveItem(Ext.getCmp("containerInicial"));
                        },
                        height: '90%',
                        right: '5%',
                        top: '5%',
                        width: '20%',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                height: '70%',
                left: '7.5%',
                top: '5%',
                width: '85%',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Name'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Surname'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Country'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Purpose',
                        options: [
                            {
                                text: 'Professional',
                                value: 'first'
                            },
                            {
                                text: 'Academic',
                                value: 'second'
                            },
                            {
                                text: 'Amateur',
                                value: 'third'
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        label: 'Institution',
                        placeHolder: 'Optional'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Employment',
                        placeHolder: 'Optional'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Email'
                    },
                    {
                        xtype: 'passwordfield',
                        label: 'Password'
                    },
                    {
                        xtype: 'passwordfield',
                        label: 'Repeat password'
                    }
                ]
            },
            {
                xtype: 'button',
                bottom: '5%',
                docked: 'bottom',
                left: '20%',
                ui: 'action',
                width: '60%',
                text: 'Done'
            }
        ]
    }

});