/*
 * File: app/view/containerHome.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerHome', {
    extend: 'Ext.Container',
    alias: 'widget.containerhome',

    config: {
        id: 'containerHome',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'container',
                height: '25%',
                id: 'containerHeader',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'container',
                        height: '60%',
                        id: 'containerLogoSupIzquierda',
                        left: '5%',
                        top: '20%',
                        width: '20%'
                    },
                    {
                        xtype: 'container',
                        height: '60%',
                        id: 'containerLogoSupDerecha',
                        right: '5%',
                        top: '20%',
                        width: '20%'
                    },
                    {
                        xtype: 'container',
                        height: '40%',
                        html: '<center> <p style=\'font-size:300%; font-face:Garamond;\'>ACE</p></center>',
                        id: 'containerMainTitle',
                        left: '30%',
                        top: '30%',
                        width: '40%'
                    },
                    {
                        xtype: 'container',
                        height: '20%',
                        html: '<center> <p style=\'font-size:120%; font-face:Garamond;\'>Automated Sport Analysis System</p></center>',
                        id: 'containerSloganMain',
                        left: '0%',
                        top: '75%',
                        width: '100%'
                    }
                ]
            },
            {
                xtype: 'panel',
                height: '60%',
                html: '<font color=\'gray\'><center><p>&nbsp</p><p style=\'font-size:180%;\'>Description</p><p>&nbsp</p><p style=\'font-size:110%;\'>The purpose of this research line is to develop computational modelling systems for the automated analysis of sports, with the aim to provide effective and efficient mechanisms for obtaining relevant information to interpret the sports in the interest of several related groups: coaches, journalists, sports scientists, physical therapists, and others. The investigated algorithms cover the perception stages in order to obtain relevant information taken from sensors, like video cameras, and the cognition stages to build the interpretation models for representing the actions, events and episodes occurred during the performed activities. Currently, the main sport being studied is association football, with the research project Automated Football Player Tracking from TV Broadcast, but the intention in the near future is to extend our current system to other outdoor games, such as hockey, and rugby; as well as martial arts.</p></center></font>',
                left: '5%',
                top: '35%',
                width: '90%',
                modal: false,
                scrollable: 'vertical'
            }
        ]
    }

});