/*
 * File: app/view/containerHome.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerHome', {
    extend: 'Ext.Container',
    alias: 'widget.containerhome',

    config: {
        id: 'containerHome',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'container',
                height: '25%',
                id: 'containerVideosPopulares',
                left: 0,
                top: 0,
                width: '100%',
                layout: {
                    align: 'start',
                    type: 'hbox'
                },
                scrollable: 'horizontal'
            },
            {
                xtype: 'container',
                height: '75%',
                html: '<p>&nbsp</p> <font size="3"> <p align="justify">The research project \'Sensor-based, Automatic Analysis of Football Games\' is an ambitious, mid-term research project that studies the automation of these tasks. The main objectives of the project are (1) the investigation of novel computational mechanisms that enable computer systems to recognize intentional activities, (2) the development of an integrated software system to automate game interpretation and analysis, and (3) the demonstration of the impact of automated game analysis on application areas, such as sport science, football coaching, and sports entertainment.<p></font>',
                id: 'containerHomeInfo',
                left: '3%',
                top: '25%',
                width: '44%',
                layout: {
                    type: 'fit'
                }
            },
            {
                xtype: 'container',
                height: '72%',
                id: 'containerHomeVideo',
                right: '3%',
                top: '25%',
                width: '44%',
                layout: {
                    type: 'fit'
                }
            }
        ]
    }

});