/*
 * File: app/view/containerInicial.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerInicial', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer16',

    config: {
        id: 'containerInicial',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'button',
                handler: function(button, event) {
                    Ext.getCmp("panelEleccionLogInFacebookOrNot").setHidden(0);
                },
                height: '10%',
                left: '5%',
                top: '80%',
                ui: 'action',
                width: '35%',
                text: 'Log In'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    Ext.getCmp("tabPanelInicial").setActiveItem(Ext.getCmp("containerRegistroUser"));
                },
                height: '10%',
                right: '5%',
                top: '80%',
                ui: 'action',
                width: '35%',
                text: 'Register'
            },
            {
                xtype: 'panel',
                height: '50%',
                hidden: true,
                id: 'panelEleccionLogInFacebookOrNot',
                left: '5%',
                top: '5%',
                width: '90%',
                modal: true,
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        title: 'Log In with'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp("panelEleccionLogInFacebookOrNot").setHidden(1);
                            Ext.getCmp("tabPanelInicial").setActiveItem(Ext.getCmp('containerIngresoUserYPass'));



                        },
                        height: '50%',
                        text: 'Regular Log In'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            try{
                                FB.getLoginStatus(function(response) {
                                    if (response.status=="connected") {
                                        var url = '/me?fields=name,email,birthday,picture,gender';
                                        FB.api(url, function(response) {
                                            //window.open('http://graph.facebook.com/'+response.id+'/picture');
                                            //alert(response.name);
                                            //funcionAEjecutarLogeoConFacebook();
                                            MyApp.app.logInFacebookSettings();
                                            //alert(response.birthday);
                                            //alert(response.picture);
                                            //alert(response.user_birthday);
                                            //alert(response.id);
                                            //alert(response.name);
                                            //DiDi.app.getController("FuncionesGeneral").funcionEjecucionCodigoInternoFBAPI(response);
                                            //se envia por extraParams la info del usuario de FB
                                            //se modifica el boton de Usuario
                                            //Ext.getCmp("toolbarDelContainerPerfilDeUsuario").setTitle(nombreDelUsuarioPerfil);
                                        },{ perms: 'email, user_birthday,access_token' });
                                            //FUNCION QUE LLEVA A CABO LA MAYORIA DEL CODIGO INICIAL
                                            //DiDi.app.getController("FuncionesGeneral").funcionBotonLogIn();
                                            //Ext.Msg.alert('Aviso', 'Su sesión ya está iniciada y autorizada.', Ext.emptyFn);
                                        } else if (response.status=="not_authorized") {
                                            // not_authorized
                                            login();
                                        } else {
                                            // not_logged_in
                                            login();
                                        }
                                    },{ perms: 'email,user_birthday,access_token'});
                                    }
                                    catch(e){
                                        Ext.Msg.alert('Aviso', 'No se pudo conectar con Facebook.', Ext.emptyFn);
                                    }
                        },
                        height: '50%',
                        text: 'Facebook'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onContainerInicialPainted',
                event: 'painted'
            }
        ]
    },

    onContainerInicialPainted: function(element, eOpts) {
        this.setHtml("<img src='./resources/images/prisLogo.png' height='"+Ext.Viewport.getWindowHeight()*0.7+"px' width='100%'/>");
    }

});