/*
 * File: app/view/containerMyVideos.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerMyVideos', {
    extend: 'Ext.Container',
    alias: 'widget.containermyvideos',

    config: {
        id: 'containerMyVideos',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'container',
                height: '40%',
                hidden: false,
                id: 'containerMyVideosOriginal',
                itemId: 'mycontainer15',
                left: 0,
                top: 0,
                width: '50%'
            },
            {
                xtype: 'container',
                height: '85%',
                id: 'containerMyVideosCanvas',
                itemId: 'mycontainer16',
                left: '5%',
                top: '2.5%',
                width: '90%'
            },
            {
                xtype: 'container',
                height: '10%',
                id: 'containerMyVideosMenu',
                top: '89%',
                width: '100%',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //PARA CARGAR VIDEO
                            //

                        },
                        height: '100%',
                        id: 'botonSeguirJugadorVideoContainerMyVideos',
                        left: '20%',
                        width: '30%',
                        iconMask: true,
                        text: 'Load video'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                height: '15%',
                scrollable: 'horizontal',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            alert('e');
                            if(document.getElementById("videoContainerMyVideos").paused){
                                document.getElementById("videoContainerMyVideos").play();
                            }
                            else{
                                document.getElementById("videoContainerMyVideos").pause();
                            }
                        },
                        iconCls: 'arrow_right',
                        iconMask: true,
                        text: ''
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            if(this.getUi()=='normal'){
                                this.setUi('confirm');
                            }
                            else{
                                this.setUi('normal');
                            }

                            //Se hace el cambio de estado en la variable para
                            //habilitado del dibujado en el canvas, y se modifica
                            //al mismo tiempo el ui del boton
                            if(variableHabilitarDibujado===0){
                                variableHabilitarDibujado=1;
                                //Ext.getCmp("botonSeguirJugadorVideoContainerMyVideos").setUi("action");
                                //Ext.getCmp("botonSeguirJugadorVideoContainerMyVideos").setText("Siguiendo jugador");
                            }
                            else{
                                variableHabilitarDibujado=0;
                                //Ext.getCmp("botonSeguirJugadorVideoContainerMyVideos").setUi("normal");
                                //Ext.getCmp("botonSeguirJugadorVideoContainerMyVideos").setText("Seguir jugador");
                            }
                        },
                        text: 'Follow'
                    }
                ]
            }
        ]
    }

});