/*
 * File: app/view/containerInicial.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerInicial', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer16',

    config: {
        id: 'containerInicial',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'button',
                handler: function(button, event) {
                    Ext.getCmp("panelEleccionLogInFacebookOrNot").setHidden(0);
                },
                height: '10%',
                left: '5%',
                top: '80%',
                ui: 'action',
                width: '35%',
                text: 'Log In'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    Ext.getCmp("tabPanelInicial").setActiveItem(Ext.getCmp("containerRegistroUser"));
                },
                height: '10%',
                right: '5%',
                top: '80%',
                ui: 'action',
                width: '35%',
                text: 'Register'
            },
            {
                xtype: 'panel',
                height: '50%',
                hidden: true,
                id: 'panelEleccionLogInFacebookOrNot',
                left: '5%',
                top: '5%',
                width: '90%',
                modal: true,
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        title: 'Log In with'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp("panelEleccionLogInFacebookOrNot").setHidden(1);
                            Ext.getCmp("tabPanelInicial").setActiveItem(Ext.getCmp("containerIngresoUserYPass"));
                        },
                        height: '50%',
                        text: 'Regular Log In'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp("panelEleccionLogInFacebookOrNot").setHidden(1);
                            Ext.getCmp("tabPanelInicial").setActiveItem(Ext.getCmp("containerMain"));
                        },
                        height: '50%',
                        text: 'Facebook'
                    }
                ]
            }
        ]
    }

});