/*
 * File: app/view/tabPanelPrincipal.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.tabPanelPrincipal', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.tabpanelprincipal',

    requires: [
        'MyApp.view.containerHome',
        'MyApp.view.containerProfile',
        'MyApp.view.containerMyVideos',
        'MyApp.view.containerStatistics'
    ],

    config: {
        id: 'tabPanelPrincipal',
        width: '100%',
        layout: {
            animation: 'fade',
            type: 'card'
        },
        tabBar: {
            docked: 'bottom',
            height: '15%',
            style: 'background: #323C46',
            scrollable: 'horizontal',
            layout: {
                pack: 'center',
                type: 'hbox'
            }
        },
        items: [
            {
                xtype: 'containerhome',
                iconCls: 'home',
                title: 'Home'
            },
            {
                xtype: 'containerprofile',
                hidden: true,
                title: 'My Profile',
                iconCls: 'info'
            },
            {
                xtype: 'containermyvideos',
                iconCls: 'action',
                title: 'Videos'
            },
            {
                xtype: 'containerPopular',
                iconCls: 'bookmarks',
                title: 'Statistics'
            }
        ],
        listeners: [
            {
                fn: 'onTabPanelMainActiveItemChange',
                event: 'activeitemchange'
            }
        ]
    },

    onTabPanelMainActiveItemChange: function(container, value, oldValue, eOpts) {
        //En caso de que se  pase hacia el containerMyVideos, entonces se obtiene
        //el objeto canvas del container para dibujar el video, y ademas se
        //pone un 1 para que se siga dibujando sobre el canvas las lineas que
        //se han trazado
        if(value==Ext.getCmp("containerMyVideos")){
            variableParaDetenerDibujado=1;
        }
        //Si se sale del containerMyVideos, se deshabilita el REdibujado
        if(oldValue==Ext.getCmp("containerMyVideos")){
            //variableParaDetenerDibujado=0;
        }
        //Se habilita el REdibujado
        //variableBoolParaDetencionDraw=1;
    }

});