/*
 * File: app/model/modelListadoTotalDeLasEmpresas.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.modelListadoTotalDeLasEmpresas', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'idCliente'
            },
            {
                name: 'nombre'
            },
            {
                name: 'descripcion'
            },
            {
                name: 'telefono'
            },
            {
                name: 'subcategoria'
            },
            {
                name: 'provincia'
            },
            {
                name: 'canton'
            },
            {
                name: 'distrito'
            },
            {
                name: 'tipoPlan'
            },
            {
                name: 'latitud'
            },
            {
                name: 'longitud'
            },
            {
                name: 'logo'
            },
            {
                name: 'banner'
            },
            {
                name: 'categoria'
            },
            {
                name: 'idUsuarioEmpresaFavorita'
            }
        ]
    }
});